//! Turning a warrant's bounds into a confinement profile something else can enforce.
//!
//! # What this is, said before anything else
//!
//! **This module emits a command line. It enforces nothing.** A profile that is never launched
//! confines nothing at all, and a bound does not move from
//! [`BoundStrength::Observed`](crate::BoundStrength::Observed) to
//! [`Enforced`](crate::BoundStrength::Enforced) because a file describing it exists.
//! [`crate::bound_strengths`] is unchanged by this module and must stay unchanged by it.
//!
//! # Why it exists anyway
//!
//! `docs/W1-delivery-gaps.md` §3.1 is the one open item where the product's central sentence is
//! stronger than what the code earns: `write_paths` is **Observed**, there is no netns, no seccomp
//! and no firewall, and the honest advice has always been "compose with a real sandbox". That
//! advice was unactionable. An operator who accepted it had to read the warrant, work out which of
//! its bounds a sandbox could hold, and hand-write a `bwrap` line — and the interesting part of
//! that job is not the typing, it is knowing **which bounds a sandbox cannot express at all**.
//!
//! This makes the advice executable and, more usefully, makes the gaps in it explicit.
//!
//! # The asymmetry that makes this worth a module
//!
//! A confinement profile can be **stricter than the warrant**, and that is its own failure.
//! `bubblewrap --unshare-net` is all-or-nothing: there is no host allowlist in a network
//! namespace. So a warrant permitting `api.github.com` produces a profile that denies *all*
//! network — the agent then fails at its first fetch, the operator concludes Warrantor is broken,
//! and the profile that caused it was generated by Warrantor.
//!
//! [`Divergence`] names both directions. A bound the sandbox cannot hold is a gap; a bound the
//! sandbox holds *harder than the warrant asked* is a break. Neither may be silent, and the second
//! is the one nobody expects.
//!
//! # Verified against a real kernel, and what that found
//!
//! The derivation below is unit-tested. It has also, since 2026-08-17, been **executed**: built for
//! Linux and run under bubblewrap on a 6.18 kernel with unprivileged user namespaces, against a
//! warrant granted with `--write 'src/**'` on a real git worktree.
//!
//! Three of the four claims held on the first run. The fourth did not, and it was mine:
//!
//! | claim | result |
//! |---|---|
//! | a write inside the worktree succeeds and persists to the host | held |
//! | a write to `$HOME` or `/etc` fails at the syscall | held — `EROFS`, "Read-only file system" |
//! | with no egress granted, DNS does not resolve | held — `getent` exits 2 inside, 0 outside |
//! | *"a write outside the worktree FAILS at the syscall"* | **false for `/tmp`** |
//!
//! `--tmpfs /tmp` gives the sandbox a private `/tmp`, so a write there **succeeds**, stays readable
//! for the rest of the session, and is silently discarded at exit. That is a third outcome the
//! sentence did not have a word for: not refused, not persisted. An operator told "fails at the
//! syscall" would wait for an error that never arrives, and an agent using `/tmp` as durable
//! scratch is never told its work evaporated. The `write_paths` sentence now names it.
//!
//! Finding that required running it. Every unit test in this file passed before and after; nothing
//! in a derivation can tell you what a kernel does with it.
//!
//! What remains outside this crate's claim: whether bubblewrap is correct is bubblewrap's claim,
//! not Warrantor's, and one kernel is not every kernel — WSL2's 6.18 is not a hardened distro
//! kernel with `unprivileged_userns_clone` disabled, where `bwrap` will refuse to start at all.

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};

use crate::WarrantBounds;

/// The confinement tools this module can write a profile for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Confinement {
    /// `bubblewrap` — unprivileged user namespaces, per-path bind mounts, optional netns.
    ///
    /// The default because it is the only one of the two that expresses a *read-only everything
    /// else* filesystem without a policy language, which is the shape `write_paths` needs.
    Bubblewrap,
    /// `firejail` — profile-driven, more widely packaged, coarser.
    Firejail,
}

impl Confinement {
    /// The word it is written as.
    #[must_use]
    pub const fn word(self) -> &'static str {
        match self {
            Self::Bubblewrap => "bubblewrap",
            Self::Firejail => "firejail",
        }
    }

    /// Parse one.
    ///
    /// # Errors
    /// A sentence naming the two, because a typo silently selecting the wrong confinement is worse
    /// than a refusal.
    pub fn parse(word: &str) -> Result<Self, String> {
        match word.trim() {
            "bubblewrap" | "bwrap" => Ok(Self::Bubblewrap),
            "firejail" => Ok(Self::Firejail),
            other => Err(format!(
                "{other:?} is not a confinement this build writes profiles for. The two are: \
                 bubblewrap, firejail."
            )),
        }
    }

    /// The platform this profile runs on. Both are Linux-only, and saying so is the point.
    #[must_use]
    pub const fn platform(self) -> &'static str {
        "linux"
    }
}

/// A bound and how the emitted profile relates to it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum Divergence {
    /// The profile holds this bound at least as tightly as the warrant states it.
    Held {
        /// The bound's name, as [`crate::bound_strengths`] spells it.
        bound: String,
        /// How, in one sentence.
        how: String,
    },
    /// The profile cannot express this bound at all. It stays exactly as strong as it was.
    Gap {
        /// The bound.
        bound: String,
        /// Why no confinement of this kind can hold it, and what does.
        why: String,
    },
    /// The profile is **stricter** than the warrant. The agent will be refused things the warrant
    /// permits, and the refusal will not look like Warrantor.
    Overreach {
        /// The bound.
        bound: String,
        /// What the warrant permits that this profile denies.
        why: String,
    },
}

impl Divergence {
    /// The bound this is about.
    #[must_use]
    pub fn bound(&self) -> &str {
        match self {
            Self::Held { bound, .. } | Self::Gap { bound, .. } | Self::Overreach { bound, .. } => {
                bound
            }
        }
    }

    /// The word a listing renders.
    #[must_use]
    pub const fn word(&self) -> &'static str {
        match self {
            Self::Held { .. } => "held",
            Self::Gap { .. } => "gap",
            Self::Overreach { .. } => "OVERREACH",
        }
    }
}

/// A confinement profile: the command, and an honest account of what it does and does not do.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Profile {
    /// Which tool.
    pub confinement: Confinement,
    /// The argv prefix. The agent's own command follows it.
    ///
    /// A prefix rather than a whole command line: this module does not know what the operator runs,
    /// and inventing an agent invocation would produce something that looks runnable and is not.
    pub argv: Vec<String>,
    /// Every bound, and how this profile relates to it. Never a subset — a bound missing from this
    /// list would be one nobody was told about.
    pub divergences: Vec<Divergence>,
    /// The sentence this profile carries about its own limits.
    pub caveat: String,
}

/// The caveat every profile carries.
///
/// In the profile rather than only in this module's docs, because the person who most needs it is
/// the one about to paste the command, and they are not reading rustdoc.
pub const PROFILE_CAVEAT: &str =
    "This is a COMMAND, not an enforcement. Nothing is confined until you launch the agent under \
     it, and Warrantor cannot tell whether you did -- `warrantor report` will still say \
     write_paths is Observed, because from this store's point of view it is. The confinement is \
     bubblewrap's or firejail's claim, not Warrantor's. Read the divergences below before using \
     it: a profile that is STRICTER than the warrant will break the agent in a way that does not \
     look like Warrantor refusing anything.";

/// Whether a path can appear in a Linux confinement command at all.
///
/// # Why this is a refusal and not a warning
///
/// The first live run of `warrantor sandbox` on Windows emitted
/// `bwrap --bind 'M:\wt-depth\.warrantor\wrt_...'` — a syntactically perfect command containing a
/// path that cannot exist on the only platform it runs on. It reads as runnable. Pasted into a
/// Linux shell it fails with bwrap's own error about a missing path, which names the symptom and
/// not the cause, and the operator is left debugging a sandbox rather than a store that was made
/// on another operating system.
///
/// A command that cannot work must not be printed as though it could. That is the same rule the
/// `--upstream` defect established: naming a remedy that does not exist costs more than naming
/// none.
///
/// # Errors
/// A sentence naming the path and what to do about it.
pub fn check_worktree(worktree: &str) -> Result<(), String> {
    // `char::from(92)` is a backslash. Written this way because every attempt to embed the
    // literal through the tooling that generated this file mangled the escape, and a mangled
    // escape here silently stops detecting Windows paths -- the exact defect this guards.
    let has_backslash = worktree.contains(char::from(92));
    if worktree.starts_with('/') && !has_backslash {
        return Ok(());
    }
    Err(format!("{worktree:?} is not an absolute POSIX path, and every confinement this module writes for is Linux-only. A profile naming this path would be a command that LOOKS runnable and cannot be: pasted into a Linux shell it fails with the sandbox's own error about a missing directory, which names the symptom and not the cause. This store was almost certainly created on Windows or macOS -- grant the warrant on the host that will run the agent, or translate the path yourself and pass it deliberately."))
}

/// Write a confinement profile for one warrant's bounds.
///
/// `worktree` is the one path the agent must be able to write. Everything else the profile mounts
/// is read-only, which is the whole reason `write_paths` is expressible at all here.
///
/// # The choice not to translate `write_paths` glob-by-glob
///
/// `write_paths` holds globs relative to the worktree (`src/**`), and a bind mount takes paths. A
/// profile that bound each glob's *directory* read-write would be wrong in the direction that
/// matters: `src/**` would become a read-write `src/`, and an agent writing `src/anything` would be
/// permitted by the sandbox and refused by the warrant. The sandbox would then be *looser* than the
/// bound while appearing to enforce it, which is worse than not enforcing it at all.
///
/// So the worktree is bound read-write as a whole and the glob refinement stays where it already
/// is — with settle, which does not stage out-of-bounds paths. The profile reports this as
/// [`Divergence::Held`] against *containment*, and the sentence says exactly how much it holds.
#[must_use]
pub fn profile(bounds: &WarrantBounds, worktree: &str, confinement: Confinement) -> Profile {
    let mut argv: Vec<String> = Vec::new();
    let mut divergences: Vec<Divergence> = Vec::new();

    match confinement {
        Confinement::Bubblewrap => {
            argv.push("bwrap".to_string());
            // Read-only root, then one read-write hole. Order matters to bwrap: later binds win, so
            // the worktree must come after the root bind or it is shadowed read-only.
            argv.extend(["--ro-bind", "/", "/"].map(String::from));
            argv.extend(["--dev", "/dev"].map(String::from));
            argv.extend(["--proc", "/proc"].map(String::from));
            argv.extend(["--tmpfs", "/tmp"].map(String::from));
            argv.extend(["--bind", worktree, worktree].map(String::from));
            argv.extend(["--chdir", worktree].map(String::from));
            // The agent must not outlive the sandbox, which is the same property the supervisor
            // already holds with a job object and PR_SET_PDEATHSIG.
            argv.push("--die-with-parent".to_string());
            argv.push("--new-session".to_string());
        }
        Confinement::Firejail => {
            argv.push("firejail".to_string());
            argv.push("--quiet".to_string());
            argv.push("--noprofile".to_string());
            argv.push(format!("--whitelist={worktree}"));
            argv.push("--read-only=/".to_string());
            argv.push(format!("--read-write={worktree}"));
            argv.push("--private-tmp".to_string());
            argv.push(format!("--chdir={worktree}"));
        }
    }

    divergences.push(Divergence::Held {
        bound: "write_paths".to_string(),
        how: format!(
            "everything outside {worktree} is mounted read-only, so a write to a real path outside \
             the worktree FAILS at the syscall with EROFS rather than being noticed at settle -- \
             verified against bubblewrap on Linux 6.18, where $HOME and /etc both refuse with \
             \"Read-only file system\". THE EXCEPTION IS /tmp, which this profile replaces with a \
             private tmpfs: a write there SUCCEEDS, stays visible to the agent for the rest of the \
             session, and is discarded when the sandbox exits. That is contained, and it is NOT \
             refused -- an agent treating /tmp as durable scratch is not told otherwise. The glob \
             refinement inside the worktree ({}) is NOT expressed here and stays where it already \
             is: settle does not stage out-of-bounds paths. Binding each glob's directory \
             read-write would make the sandbox LOOSER than the bound while appearing to enforce it.",
            if bounds.write_paths.is_empty() {
                "none granted".to_string()
            } else {
                bounds.write_paths.iter().cloned().collect::<Vec<_>>().join(", ")
            }
        ),
    });

    // ── network ───────────────────────────────────────────────────────────────────────
    //
    // The asymmetry this module exists to surface. A network namespace is all-or-nothing.
    if bounds.egress_hosts.is_empty() {
        match confinement {
            Confinement::Bubblewrap => argv.push("--unshare-net".to_string()),
            Confinement::Firejail => argv.push("--net=none".to_string()),
        }
        divergences.push(Divergence::Held {
            bound: "egress_hosts".to_string(),
            how: "the warrant grants no egress and the profile unshares the network namespace, so \
                  there is no route out even for a process that never touches the MCP proxy. This \
                  is the one case where a sandbox turns egress_hosts from Mediated into something \
                  an agent cannot route around."
                .to_string(),
        });
    } else {
        // Deliberately NOT emitted. A profile that silently denied permitted egress would break the
        // agent, and the operator would blame the wrong thing.
        divergences.push(Divergence::Overreach {
            bound: "egress_hosts".to_string(),
            why: format!(
                "this warrant permits {} host(s) ({}), and a network namespace has no host \
                 allowlist -- it is all or nothing. `--unshare-net` is therefore NOT in the command \
                 above: adding it would deny egress the warrant grants, the agent would fail at its \
                 first fetch, and nothing in that failure would look like a bound refusing \
                 anything. Egress stays Mediated, held by the MCP proxy. To make it enforced, put a \
                 filtering proxy in the namespace and allow only that.",
                bounds.egress_hosts.len(),
                bounds.egress_hosts.iter().cloned().collect::<Vec<_>>().join(", ")
            ),
        });
    }

    // ── the bounds no filesystem or network confinement can hold ──────────────────────
    divergences.push(Divergence::Gap {
        bound: "tools".to_string(),
        why: "a tool allowlist is a property of the MCP conversation, not of the process. A \
              sandbox cannot tell a permitted tool call from a refused one because both arrive as \
              the same syscalls. Stays Mediated, held by the proxy."
            .to_string(),
    });
    divergences.push(Divergence::Gap {
        bound: "staged_classes".to_string(),
        why: "staging is a decision about what to DO with an effect, taken after the effect is \
              described. No confinement expresses it. Stays Mediated."
            .to_string(),
    });
    divergences.push(Divergence::Gap {
        bound: "budget_cents_observed".to_string(),
        why: "the budget is parsed from the agent's own self-reporting and no sandbox can meter \
              tokens. Stays Observed, and its name says so."
            .to_string(),
    });
    divergences.push(Divergence::Gap {
        bound: "delegation_depth".to_string(),
        why: "held by an Ed25519 signature, which is already stronger than anything a sandbox \
              adds. Stays Enforced."
            .to_string(),
    });
    divergences.push(Divergence::Gap {
        bound: "expires_at".to_string(),
        why: "held by the supervisor's OS process link -- a Windows job object, or setsid plus \
              PR_SET_PDEATHSIG. `--die-with-parent` above reinforces it and does not replace it. \
              Stays Enforced."
            .to_string(),
    });

    Profile {
        confinement,
        argv,
        divergences,
        caveat: PROFILE_CAVEAT.to_string(),
    }
}

impl Profile {
    /// Every bound this profile is stricter about than the warrant.
    #[must_use]
    pub fn overreaches(&self) -> Vec<&Divergence> {
        self.divergences
            .iter()
            .filter(|d| matches!(d, Divergence::Overreach { .. }))
            .collect()
    }

    /// The bounds this profile actually holds.
    #[must_use]
    pub fn held(&self) -> Vec<&Divergence> {
        self.divergences
            .iter()
            .filter(|d| matches!(d, Divergence::Held { .. }))
            .collect()
    }

    /// The command as a single shell line.
    ///
    /// Each argument is single-quoted unless it is already safe, because a worktree path can hold a
    /// space and a profile that breaks on one is a profile nobody uses twice.
    #[must_use]
    pub fn shell_line(&self) -> String {
        self.argv
            .iter()
            .map(|a| shell_quote(a))
            .collect::<Vec<_>>()
            .join(" ")
    }
}

/// Quote one argument for a POSIX shell.
///
/// Single quotes, with the standard `'\''` escape for an embedded single quote. Not a general
/// shell-escaping library — it handles exactly the arguments this module produces, which are a
/// fixed set of flags plus one operator-supplied path.
fn shell_quote(argument: &str) -> String {
    let safe = !argument.is_empty()
        && argument
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "-_./=:".contains(c));
    if safe {
        return argument.to_string();
    }
    format!("'{}'", argument.replace('\'', r"'\''"))
}

/// The set of bound names a profile must speak about.
///
/// Taken from [`crate::bound_strengths`] rather than written out again, so a bound added there
/// without being considered here is a test failure rather than a silent omission from every
/// profile this module writes.
#[must_use]
pub fn bounds_to_cover() -> BTreeSet<&'static str> {
    crate::bound_strengths()
        .into_iter()
        .map(|(name, _)| name)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::SideEffectClass;

    fn bounds(write: &[&str], egress: &[&str]) -> WarrantBounds {
        WarrantBounds {
            tools: ["github.create_pr"].into_iter().map(String::from).collect(),
            write_paths: write.iter().map(|s| (*s).to_string()).collect(),
            egress_hosts: egress.iter().map(|s| (*s).to_string()).collect(),
            staged_classes: [SideEffectClass::Write].into_iter().collect(),
            expires_at: 1_786_000_000,
            budget_cents_observed: Some(500),
            delegation_depth: 1,
        }
    }

    #[test]
    fn every_bound_the_product_reports_is_spoken_about_by_every_profile() {
        // The rule that keeps this module honest as the product grows. A bound added to
        // `bound_strengths` without being considered here would silently vanish from every profile,
        // and the operator would have no way to know a confinement said nothing about it.
        for confinement in [Confinement::Bubblewrap, Confinement::Firejail] {
            for b in [bounds(&["src/**"], &[]), bounds(&[], &["api.github.com"])] {
                let profile = profile(&b, "/home/u/wt", confinement);
                let spoken: BTreeSet<&str> =
                    profile.divergences.iter().map(Divergence::bound).collect();
                for bound in bounds_to_cover() {
                    assert!(
                        spoken.contains(bound),
                        "{} says nothing about {bound}",
                        confinement.word()
                    );
                }
            }
        }
    }

    #[test]
    fn a_warrant_with_egress_does_not_get_a_network_namespace() {
        // The finding this module exists for. `--unshare-net` is all-or-nothing, so emitting it for
        // a warrant that PERMITS egress would deny what the warrant grants: the agent fails at its
        // first fetch and nothing in that failure looks like a bound refusing anything.
        let b = bounds(&["src/**"], &["api.github.com", "crates.io"]);
        let profile = profile(&b, "/home/u/wt", Confinement::Bubblewrap);
        assert!(
            !profile.argv.iter().any(|a| a == "--unshare-net"),
            "a permitted-egress warrant must not be handed an all-or-nothing netns: {:?}",
            profile.argv
        );
        let over = profile.overreaches();
        assert_eq!(over.len(), 1);
        assert_eq!(over[0].bound(), "egress_hosts");
        let Divergence::Overreach { why, .. } = over[0] else {
            unreachable!()
        };
        assert!(why.contains("api.github.com"), "{why}");
        assert!(why.contains("all or nothing"), "{why}");
    }

    #[test]
    fn a_warrant_with_no_egress_does_get_one_and_that_is_the_one_real_upgrade() {
        let b = bounds(&["src/**"], &[]);
        let profile = profile(&b, "/home/u/wt", Confinement::Bubblewrap);
        assert!(profile.argv.iter().any(|a| a == "--unshare-net"));
        assert!(profile.overreaches().is_empty());
        let held: Vec<&str> = profile.held().iter().map(|d| d.bound()).collect();
        assert!(held.contains(&"egress_hosts"), "{held:?}");
        assert!(held.contains(&"write_paths"), "{held:?}");
    }

    #[test]
    fn firejail_makes_the_same_two_decisions_as_bubblewrap() {
        // Different flags, same policy. If the two ever disagreed about whether a warrant's egress
        // gets a namespace, one of them would be quietly wrong.
        for (write, egress, expect_netns) in [
            (vec!["src/**"], vec![], true),
            (vec!["src/**"], vec!["api.github.com"], false),
        ] {
            let b = bounds(&write, &egress);
            let bwrap = profile(&b, "/home/u/wt", Confinement::Bubblewrap);
            let jail = profile(&b, "/home/u/wt", Confinement::Firejail);
            assert_eq!(
                bwrap.argv.iter().any(|a| a == "--unshare-net"),
                expect_netns
            );
            assert_eq!(jail.argv.iter().any(|a| a == "--net=none"), expect_netns);
            assert_eq!(
                bwrap.overreaches().len(),
                jail.overreaches().len(),
                "the two confinements disagreed about overreach"
            );
        }
    }

    #[test]
    fn the_worktree_bind_comes_after_the_read_only_root() {
        // bwrap applies binds in order and later ones win. A worktree bound BEFORE `--ro-bind / /`
        // is shadowed read-only, and the agent cannot write its own worktree -- a profile that
        // looks right, runs, and breaks everything.
        let profile = profile(
            &bounds(&["src/**"], &[]),
            "/home/u/wt",
            Confinement::Bubblewrap,
        );
        let ro_root = profile
            .argv
            .iter()
            .position(|a| a == "--ro-bind")
            .expect("a read-only root");
        let rw_tree = profile
            .argv
            .iter()
            .position(|a| a == "--bind")
            .expect("a read-write worktree");
        assert!(
            rw_tree > ro_root,
            "the worktree bind must come after the root bind or it is shadowed: {:?}",
            profile.argv
        );
    }

    #[test]
    fn the_write_paths_sentence_refuses_to_claim_the_globs_are_enforced() {
        // The trap: binding each glob's DIRECTORY read-write makes `src/**` into a read-write
        // `src/`, so the sandbox permits what the warrant refuses -- looser than the bound while
        // appearing to enforce it, which is worse than not enforcing it.
        let profile = profile(
            &bounds(&["src/**"], &[]),
            "/home/u/wt",
            Confinement::Bubblewrap,
        );
        let Some(Divergence::Held { how, .. }) = profile
            .divergences
            .iter()
            .find(|d| d.bound() == "write_paths")
        else {
            panic!("write_paths must be spoken about");
        };
        assert!(how.contains("NOT expressed here"), "{how}");
        assert!(how.contains("settle"), "{how}");
    }

    #[test]
    fn the_write_paths_sentence_names_the_tmpfs_exception() {
        // Found by RUNNING the profile, not by deriving it. `--tmpfs /tmp` means a write under
        // /tmp succeeds, stays readable for the session, and is discarded at exit -- a third
        // outcome the original sentence ("a write outside the worktree FAILS at the syscall") had
        // no word for. Not refused, not persisted.
        //
        // Every unit test in this file passed before that run and after it. Nothing in a
        // derivation can tell you what a kernel does with it.
        let profile = profile(
            &bounds(&["src/**"], &[]),
            "/home/u/wt",
            Confinement::Bubblewrap,
        );
        let Some(Divergence::Held { how, .. }) = profile
            .divergences
            .iter()
            .find(|d| d.bound() == "write_paths")
        else {
            panic!("write_paths must be spoken about");
        };
        assert!(
            how.contains("/tmp"),
            "the profile mounts a tmpfs over /tmp and must say what that means: {how}"
        );
        assert!(
            how.contains("discarded"),
            "a write that succeeds and vanishes is neither refused nor persisted, and the              sentence has to say which: {how}"
        );
        // The tmpfs is in the argv, so the sentence is describing this profile and not a general
        // fact about bubblewrap.
        assert!(profile.argv.iter().any(|a| a == "--tmpfs"));
    }

    #[test]
    fn a_worktree_path_with_a_space_survives_the_shell_line() {
        let profile = profile(
            &bounds(&["src/**"], &[]),
            "/home/u/my worktree",
            Confinement::Bubblewrap,
        );
        let line = profile.shell_line();
        assert!(line.contains("'/home/u/my worktree'"), "{line}");
        // A flag must not be quoted: a line full of quoted flags is one nobody trusts.
        assert!(line.contains(" --die-with-parent"), "{line}");
    }

    #[test]
    fn a_quote_in_a_path_cannot_break_out_of_the_quoting() {
        let profile = profile(&bounds(&[], &[]), "/home/u/it's", Confinement::Bubblewrap);
        assert!(profile.shell_line().contains(r"'/home/u/it'\''s'"));
    }

    #[test]
    fn the_caveat_says_the_profile_enforces_nothing_by_existing() {
        let profile = profile(
            &bounds(&["src/**"], &[]),
            "/home/u/wt",
            Confinement::Bubblewrap,
        );
        assert!(profile.caveat.contains("COMMAND, not an enforcement"));
        assert!(
            profile.caveat.contains("Observed"),
            "the report will still say Observed and the profile has to say so first"
        );
    }

    #[test]
    fn a_path_that_cannot_exist_on_linux_is_refused_before_a_command_is_printed() {
        // Found by running the command on Windows: it emitted
        // `bwrap --bind 'M:\wt-depth\...'`, a syntactically perfect line naming a path that
        // cannot exist on the only platform bwrap runs on. It reads as runnable.
        assert!(check_worktree("/home/u/wt").is_ok());
        assert!(check_worktree("/home/u/my worktree").is_ok());

        for bad in [
            r"M:\wt-depth\.warrantor\wrt_1",
            r"C:\Users\u\wt",
            "relative/path",
            "",
        ] {
            let error = check_worktree(bad).expect_err("{bad} must be refused");
            assert!(error.contains("Linux-only"), "{error}");
        }
    }

    #[test]
    fn an_unknown_confinement_is_refused_rather_than_defaulted() {
        assert!(Confinement::parse("bwrap").is_ok());
        assert!(Confinement::parse("firejail").is_ok());
        let error = Confinement::parse("docker").expect_err("not a confinement this writes");
        assert!(error.contains("bubblewrap, firejail"), "{error}");
    }
}
