"""Rust decides the authority arithmetic; the Python mirror must agree on every vector.

``warrantor_ml.tasks.bounds`` re-implements ``WarrantBounds::contains`` so the bound proposer can
be scored on over-grant rate. That is a second implementation of authority arithmetic, and a
second implementation can disagree with the first -- at which point the metric the model is
judged on is measuring the wrong thing.

The fixture is produced by ``rust/warrant/examples/emit_bounds_vectors.rs`` and regenerated by
``tools/ci/run_python_checks.py`` before every test run. When it is missing these tests **fail**
rather than skip: an interop test that skips silently is a safety net that reports success
without being exercised, which is the failure mode ``run_python_checks.py``'s own comment names.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from warrantor_ml.tasks.bounds import ReferenceBounds, authority_expansions

FIXTURE = Path(__file__).resolve().parents[3] / ".bounds_interop.json"


def _load() -> list[dict[str, object]]:
    if not FIXTURE.exists():
        pytest.fail(
            f"{FIXTURE} is missing. Produce it with:\n"
            "    cargo run -p warrantor-warrant --example emit_bounds_vectors -- "
            f"{FIXTURE}\n"
            "This test fails rather than skips on purpose: a cross-language check that skips "
            "when its fixture is absent reports success having never run."
        )
    document = json.loads(FIXTURE.read_text(encoding="utf-8"))
    assert document["format"] == "warrantor.bounds-interop/1"
    vectors = document["vectors"]
    assert vectors, "the fixture carries no vectors"
    return list(vectors)


def _bounds(payload: dict[str, object]) -> ReferenceBounds:
    """Rebuild Rust's serialised ``WarrantBounds`` in the Python mirror's shape."""

    return ReferenceBounds(
        tools=frozenset(payload["tools"]),  # type: ignore[arg-type]
        write_paths=frozenset(payload["write_paths"]),  # type: ignore[arg-type]
        egress_hosts=frozenset(payload["egress_hosts"]),  # type: ignore[arg-type]
        staged_classes=frozenset(payload["staged_classes"]),  # type: ignore[arg-type]
        expires_at=int(payload["expires_at"]),  # type: ignore[arg-type]
        budget_cents_observed=(
            None
            if payload["budget_cents_observed"] is None
            else int(payload["budget_cents_observed"])  # type: ignore[arg-type]
        ),
        delegation_depth=int(payload["delegation_depth"]),  # type: ignore[arg-type]
    )


def test_the_fixture_covers_every_rule_the_mirror_has_to_reproduce() -> None:
    """A fixture that lost its hardest cases would pass while the mirror was wrong."""

    names = {str(vector["name"]) for vector in _load()}
    for required in (
        "staged_classes_narrowed_is_an_expansion",
        "child_outlives_parent",
        "absent_parent_budget_is_a_ceiling_of_zero",
        "child_drops_a_declared_ceiling",
        "delegation_depth_not_strictly_below",
    ):
        assert required in names, f"the interop fixture no longer covers {required!r}"


@pytest.mark.parametrize("vector", _load(), ids=lambda vector: str(vector["name"]))
def test_python_agrees_with_rust_on_every_vector(vector: dict[str, object]) -> None:
    parent = _bounds(vector["parent"])  # type: ignore[arg-type]
    child = _bounds(vector["child"])  # type: ignore[arg-type]
    expansions = authority_expansions(child, parent)
    python_contained = not expansions
    rust_contained = bool(vector["contained"])
    assert python_contained == rust_contained, (
        f"{vector['name']}: Rust says contained={rust_contained}, Python says "
        f"{python_contained}. Rule under test: {vector['rule']}. "
        f"Python's expansions: {list(expansions)}"
    )


@pytest.mark.parametrize(
    "vector",
    [item for item in _load() if not item["contained"]],
    ids=lambda vector: str(vector["name"]),
)
def test_the_mirror_blames_the_same_bound_rust_blamed(vector: dict[str, object]) -> None:
    """Agreeing on the verdict for the wrong reason would still mislead a model's scorecard."""

    parent = _bounds(vector["parent"])  # type: ignore[arg-type]
    child = _bounds(vector["child"])  # type: ignore[arg-type]
    expansions = authority_expansions(child, parent)
    rust_message = str(vector["error"])
    blamed = rust_message.split("authority: ", 1)[-1].split(":", 1)[0].strip()
    assert any(expansion.startswith(blamed) for expansion in expansions), (
        f"{vector['name']}: Rust blamed {blamed!r} but Python reported {list(expansions)}"
    )
