#!/usr/bin/env python3
"""Generate the two adoption deliverables.

  docs/html/adoption-blockers-2026-08-09.html   what stops developers and enterprises
  docs/html/operating-playbook-2026-08-09.html  the sequenced runbook + what I need from Vikram

Regenerate:  python docs/html/meta/build_adoption.py
"""
from __future__ import annotations

import pathlib

from build_critical_analysis import CSS, JS, bullets, esc, filter_bar, grade_pill, md, para, sev_pill, tag

OUT_DIR = pathlib.Path(__file__).resolve().parents[1]
DATE = "9 August 2026"
NS = "warrantor"


def shell(title: str, subtitle: str, nav_items, body: str, eyebrow: str) -> str:
    nav = "".join(
        f'<div class="grp">{g}</div>' + "".join(f'<a href="#{a}">{l}</a>' for a, l in items)
        for g, items in nav_items
    )
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title><style>{CSS}</style></head><body>
<div class="prog" id="prog"></div>
<div class="tools"><button id="expandBtn" type="button">Expand all</button>
<button id="themeBtn" type="button">Theme</button></div>
<div class="shell">
<aside class="side"><div class="brand">{esc(title)}</div>
<div class="brandsub">{esc(subtitle)}</div><nav>{nav}</nav></aside>
<main class="main">
<div class="hero"><div class="eyebrow">{eyebrow}</div>
<h1>{esc(title)}</h1><p class="lede">{subtitle}</p>
<div class="meta"><span><strong>Evidence cut:</strong> {DATE}</span>
<span><strong>Namespace:</strong> <code>{NS}</code></span>
<span><strong>Licence:</strong> Apache-2.0 throughout</span>
<span><strong>Scope:</strong> ~25 components</span></div></div>
{body}
<hr><p style="font-size:.8rem;color:var(--fg-3);max-width:none">
Generated by <code>docs/html/meta/build_adoption.py</code>. Companion to
<a href="aumos-critical-analysis-2026-08-09.html">the implementation &amp; protocol critical analysis</a>.
Evidence tags: {tag('EXECUTED')} {tag('READ')} {tag('EXTERNAL')} {tag('INFERRED')} {tag('UNVERIFIABLE')}.</p>
</main></div><script>{JS}</script></body></html>"""


# ===========================================================================
# COMPONENT VALUE TABLE — honest verdict per component
# keep: KEEP | THIN | CUT
# ===========================================================================
def C(cid, name, lang, keep, oss, ent, verdict):
    return dict(cid=cid, name=name, lang=lang, keep=keep, oss=oss, ent=ent, verdict=verdict)


COMPONENTS = [
    # ---- KEEP: genuine differentiation ----
    C("S3", "gguf-ext", "Rust", "KEEP",
      "A hardened GGUF parser with fuzz targets and fallible allocation. Publishable on its own merits &mdash; "
      "developers loading untrusted model files have no safe option today.",
      "Directly mitigates a live CVE class (CVE-2026-5760, CVSS 9.8, SSTI&rarr;RCE via a GGUF chat-template field). "
      "Buys a concrete answer to &ldquo;what stops a poisoned model file?&rdquo;",
      "<strong>The strongest single artifact in the repo.</strong> Bounded parsing, checked arithmetic, tensor-overlap "
      "detection, real RFC 8785, domain separation, 2 fuzz targets, zero <code>unwrap</code> in non-test code. Ship it "
      "as a standalone crate this month."),
    C("P8", "verifiable-evaluation-bundle", "Spec", "KEEP",
      "The only signed, independently verifiable eval format. promptfoo, Inspect, HELM and lm-eval-harness all market "
      "reproducibility; none signs, and <strong>none pins the grader</strong>.",
      "The artifact a regulator will eventually demand and nobody can currently produce. NIST AI 800-2 enumerates "
      "exactly what belongs in such a bundle and names no candidate.",
      "<strong>This is the bet.</strong> Unoccupied by Microsoft's toolkit, unoccupied by the vendors, and the one "
      "place a small team can define the standard rather than chase it. Shortest path: a DSSE/in-toto envelope over "
      "an Inspect <code>.eval</code> digest."),
    C("P12", "capability-attestation-profile", "Spec", "KEEP",
      "The signed counterpart to MCP's self-admittedly untrusted <code>ToolAnnotations</code>. MCP's own spec says "
      "annotations are untrusted hints and its registry signs nothing.",
      "Composite attestation &mdash; CPU quote + GPU EAT + container measurement + <strong>model-weight hash + "
      "serving-stack version</strong> in one verdict. Eight attested-inference providers, eight incompatible verifiers.",
      "Real whitespace <em>above</em> the primitives, never at them. NVIDIA NRAS and Intel Trust Authority are free; "
      "composition is not. Roughly a 12-month window before Veraison or CoCo close it."),
    C("R8", "sandbox-runtime", "Rust", "KEEP",
      "Genuine Wasmtime isolation: fuel metering enforced, WASI deliberately unlinked, imports admitted against a "
      "signed policy, capabilities index-addressed not string-addressed.",
      "A real enforcement primitive rather than a policy opinion. Audit-before-dispatch is fatal on failure.",
      "Careful, adversarially-minded code. Its problem is that the catalogue said it did not exist. Wire it to P5's "
      "<code>runtime</code> enum and it becomes the containment story."),
    C("F2", "dp-crate", "Python", "KEEP",
      "DPSGD with clipping, Gaussian noise and an RDP accountant. Best test-to-source ratio in the repository (458 "
      "test lines to 531).",
      "Differential privacy is a named control in RBI FREE-AI and DPDP conversations, and correctness here is provable.",
      "Solid work. Publish the privacy-accounting proofs and state the composition model explicitly &mdash; that is "
      "what turns a library into evidence."),
    C("I2", "identity-bindings", "Go", "KEEP",
      "Real SPIFFE: <code>workloadapi.NewX509Source</code>, validity windows, <code>x509svid.IDFromCert</code> "
      "cross-validated against the URI SAN, selector-injection defence.",
      "SPIFFE is the de-facto workload identity standard and this is a correct integration.",
      "<strong>Ship this and retire <code>agent-identity</code>.</strong> The real module has zero importers while the "
      "one that formats <code>spiffe://</code> strings is what the Dockerfile deploys."),
    C("X8", "mcp-gateway", "TypeScript", "KEEP",
      "Targets MCP <code>2026-07-28</code> &mdash; ahead of the official SDK. Now verifies envelope signatures, binds "
      "keyId&rarr;issuer, enforces budgets, and implements I-11 self-change protection.",
      "The primary integration surface. Everything a partner touches goes through here.",
      "Post-AX-02 this is real. Remaining gaps are OAuth 2.1 resource-server behaviour and accepting the two "
      "most-deployed MCP revisions &mdash; both required, both bounded."),
    C("P2", "agent-action-receipt", "Spec", "THIN",
      "Signed action evidence. But RFC 9942 (COSE Receipts) and RFC 9943 (SCITT) are published Standards-Track RFCs "
      "as of June 2026.",
      "Enterprises want an audit trail; SIEMs want OCSF. Both exist.",
      "<strong>Re-express as a SCITT profile or withdraw.</strong> Defining a parallel receipt format against a "
      "published RFC pair is the fastest way to lose a standards conversation. The genuinely novel part &mdash; "
      "joining receipts to a verifiable delegation chain &mdash; survives as a profile."),
    C("E1", "flight-recorder", "Rust", "KEEP",
      "Now an <code>fsync</code>'d hash-chained append-only log where <code>PendingAction</code> cannot reach commit "
      "without durable evidence &mdash; I-07 in the type system.",
      "The evidence plane. Export to OCSF 1.9 <code>ai_agent</code> + <code>delegation</code> and it lands in Splunk, "
      "Sentinel, Elastic and Security Lake with no parser project.",
      "Fixed under AX-40. Its remaining defect is that it fabricates the policy decision it signs &mdash; close that "
      "and it is the most enterprise-legible component here."),
    C("A2", "adversaria", "Python", "THIN",
      "Adversarial corpus generation. Real code, but the detector scores success on response length.",
      "Red-teaming evidence is explicitly demanded by RBI's draft MRM guidance.",
      "Map the corpus to ATLAS v5.4.0 and OWASP ASI01&ndash;10 and publish attack-success rates the way LlamaFirewall "
      "did (17.6%&rarr;1.7%). Unmeasured red-teaming is not evidence."),
    C("X10", "sovereign-stack", "Go", "KEEP",
      "Air-gap and residency packaging. Under-invested relative to its strategic weight.",
      "<strong>The one durable advantage.</strong> Portability across AWS/Azure/GCP/on-prem, and AWS has no "
      "confidential GPU at all. CERT-In requires 180 days of ICT logs held inside India.",
      "Invest here. Sovereignty is the argument that survives &ldquo;why not the Microsoft one?&rdquo; in India and "
      "the Gulf, and it is not a technology claim Microsoft can match with a US-hosted control plane."),
    # ---- CUT: commodity ----
    C("N3", "inference-proxy", "Rust", "CUT", "&mdash;", "&mdash;",
      "LiteLLM has 56k stars with Stripe and Netflix in production. This is not a proxy (no tokio/hyper/axum) and "
      "carries a cross-tenant cache leak. <strong>Adopt LiteLLM; contribute policy hooks.</strong>"),
    C("R6", "policy-bridge", "Rust", "CUT", "&mdash;", "&mdash;",
      "OPA is CNCF-graduated, Cedar is formally verified and AWS-backed, and AWS Dogwood already extends Cedar "
      "temporally. Zero <code>EngineClient</code> implementations exist. <strong>Adopt OPA + Cedar.</strong>"),
    C("S1", "safe-tensors-pp", "Rust", "CUT", "&mdash;", "&mdash;",
      "OpenSSF Model Signing signs models <em>without modifying the file</em>, with NVIDIA NGC and Kaggle adopting. "
      "An in-file provenance block forks the format and breaks digest stability &mdash; violating the project's own "
      "stated non-goal. <strong>Adopt OMS.</strong>"),
    C("C1-1", "nvtrust-bridge", "Rust", "CUT", "&mdash;", "&mdash;",
      "NVIDIA gives away NRAS, the local verifier and <code>nvattest</code> under Apache-2.0; Intel Trust Authority "
      "verifies free on three clouds. <strong>Consume them directly</strong> and keep only the composition layer (P12)."),
    C("R4", "credential-vault", "Rust", "CUT", "&mdash;", "&mdash;",
      "HashiCorp Vault shipped a SPIFFE secrets engine. All three backends here return "
      "<code>BackendUnavailable</code>. <strong>Adopt Vault.</strong>"),
    C("R3", "kill-switch", "Rust", "THIN", "&mdash;",
      "RBI's draft MRM guidance explicitly demands a kill switch, so the <em>capability</em> is procurement-relevant.",
      "Now has a real <code>ExecutionEngine</code>, but ServiceNow ships this as a product feature and every platform "
      "has agent revocation. Keep it as a thin wrapper over the platform's own primitive rather than a component."),
    C("R7", "egress-filter", "Rust", "THIN", "&mdash;", "&mdash;",
      "Now default-deny, which was the critical fix. But Anthropic's sandbox-runtime does this at the OS boundary and "
      "four gateways do it at the network boundary. Keep only if the eBPF path is actually built."),
    C("S4", "model-sbom", "Python", "THIN", "&mdash;",
      "CISA's 2026 Minimum Elements (29 July 2026) now require an SBOM Author Signature &mdash; and CycloneDX carries "
      "it in-document while SPDX needs an external envelope.",
      "Currently emits CycloneDX 1.5 with <code>type: library</code> &mdash; not an ML-BOM in any version. Rewrite "
      "against CycloneDX 1.6 and it becomes a hard-gate artifact rather than a liability."),
]


def sec_verdict_blockers():
    return f"""
<section id="verdict">
<div class="eyebrow">01 &middot; The reframe</div>
<h2>Microsoft shipped your product in April, and that changes the question</h2>
<div class="danger"><div class="calltitle">Verified independently, 2026-08-09</div>
{para("**`microsoft/agent-governance-toolkit`** &mdash; MIT-licensed, open source, created 2026-03-02, "
      "**5,840 stars, 1,008 forks**, last push *yesterday*. Its own description: *&ldquo;Policy enforcement, "
      "zero-trust identity, execution sandboxing, and reliability engineering for autonomous AI agents.&rdquo;* "
      "Seven packages across Python, TypeScript, **Rust, Go** and .NET. Claims **&lt;0.1&nbsp;ms p99** policy "
      "enforcement and 10/10 OWASP Agentic Top 10 coverage. Ships SECURITY.md with a 24h/72h/90-day SLA, "
      "GOVERNANCE.md, MAINTAINERS.md, CodeQL, Gitleaks, ClusterFuzzLite, OpenSSF Scorecard and 992 conformance "
      "tests. [EXTERNAL, verified via GitHub API]")}</div>
{para("This inverts the objection you were expecting. The normal OSS problem is *entity risk* &mdash; who maintains "
      "this in eighteen months. A buyer can now get an open agent-governance substrate **with Microsoft behind it**, "
      "so AumOS carries the entity risk *and* has to explain the overlap. Every partner conversation from now on "
      "opens with &ldquo;why not the Microsoft one?&rdquo;")}
<div class="good"><div class="calltitle">And the answer already exists in your own audit</div>
{para("Microsoft's toolkit is a **policy and identity runtime**. It enforces decisions. It does not produce "
      "**signed, independently verifiable evidence** &mdash; an artifact a third party can check *without trusting "
      "the runner*. That is precisely the slot the competitive sweep found unoccupied by anyone: promptfoo, Inspect, "
      "HELM and lm-eval-harness all market reproducibility and **none of them signs anything or pins the grader**.")}
{para("So the defensible line is not &ldquo;we govern agents better.&rdquo; It is: **enforcement is commodity; "
      "verifiable evidence is not.** Let Microsoft, AWS Cedar and Envoy do enforcement. Be the layer that makes what "
      "happened *provable to someone who was not there* &mdash; and portable across clouds, which a US-hosted "
      "control plane structurally cannot be for an Indian or Gulf regulator.")}</div>
<h3>What this means for the four use cases you named</h3>
<div class="tw"><table data-sortable>
<thead><tr><th>Partner use case</th><th>Competitive position</th><th>Honest read</th></tr></thead><tbody>
<tr><td><strong>Govern agents they already run</strong></td><td>Contested &mdash; Microsoft AGT, AWS AgentCore Policy (GA, 13 regions), Envoy AI Gateway v1.0</td><td>Fastest path to a pilot, weakest moat. Win it on <em>integration breadth</em> and portability, not on the policy engine.</td></tr>
<tr><td><strong>Prove compliance to a regulator</strong></td><td><strong>Open</strong> &mdash; no regulator in the US, India or GCC prescribes an evidence format</td><td>Strongest commercial wedge. The vacuum is the opportunity: whoever hands an examiner a coherent bundle first defines what one looks like.</td></tr>
<tr><td><strong>Attested / sovereign inference</strong></td><td>Primitives free (NVIDIA NRAS, Intel Trust Authority); <strong>composition open</strong></td><td>Real, ~12-month window. Requires real TEE hardware to stop being simulated &mdash; this is the one use case blocked on a physical dependency.</td></tr>
<tr><td><strong>Evaluate / red-team before shipping</strong></td><td><strong>Open</strong> &mdash; nobody signs an eval or pins the grader</td><td>The single most defensible bet. Also the cheapest to prove: a DSSE envelope over an Inspect <code>.eval</code> digest is weeks, not quarters.</td></tr>
</tbody></table></div>
</section>"""


def sec_gates():
    return f"""
<section id="gates">
<div class="eyebrow">02 &middot; The enterprise gate</div>
<h2>What actually blocks a regulated buyer &mdash; and what does not</h2>
{para("These are the gates a security architecture review board applies in 2026, ranked. Sources are primary where "
      "cited. The useful surprise is how much of this is cheap for a small AI-assisted team and how little of it is "
      "about code quality.")}
<h3>Hard gates &mdash; genuinely block adoption</h3>
<div class="tw"><table data-sortable>
<thead><tr><th>Gate</th><th>The actual requirement</th><th>Your state</th></tr></thead><tbody>
<tr><td><strong>&ldquo;Why not the Microsoft one?&rdquo;</strong></td><td>Not a checklist item &mdash; it precedes every other gate. Must be answered as a capability they lack, not as quality.</td><td><span class="sev sev-critical">UNANSWERED</span> Answer is verifiable evidence + sovereignty.</td></tr>
<tr><td><strong>Signed releases + provenance</strong></td><td>OpenSSF OSPS-BR-06.01: releases MUST be signed or in a signed manifest with per-asset hashes. MVSP 3.5: SLSA Build L1 provenance. Plus verification <em>instructions</em>.</td><td><span class="sev sev-critical">NONE</span> Nothing published, no releases, no tags.</td></tr>
<tr><td><strong>SBOM, CISA 2026 elements</strong></td><td>CISA/NSA/FBI <strong>2026 Minimum Elements</strong> (29 Jul 2026) supersede the 2021 NTIA set. Seven new fields incl. <strong>SBOM Author Signature</strong>, component hash + licence. CycloneDX 1.6 carries the signature in-document; SPDX needs an external envelope.</td><td><span class="sev sev-high">STALE</span> Emits CycloneDX 1.5, not an ML-BOM, and the CI step ends in <code>|| true</code>.</td></tr>
<tr><td><strong>Disclosure policy + private channel</strong></td><td>OSPS-VM-01/03/04 and MVSP 1.1/3.4: published CVD policy with a stated timeframe, private reporting, 90-day patch clock. GHSA suffices &mdash; <strong>CNA status is not required</strong>.</td><td><span class="sev sev-medium">PARTIAL</span> SECURITY.md exists but drops the CVE plan, and its PGP key does not exist.</td></tr>
<tr><td><strong>Third-party security audit</strong></td><td>CNCF makes this explicit for graduation. <strong>OSTIF, funded by OpenSSF Alpha-Omega, audits OSS at no cost to the project</strong> &mdash; including a programme covering 25 AI/LLM projects.</td><td><span class="sev sev-high">NONE</span> And the audit found a forgery in the trusted core, so this is not cosmetic.</td></tr>
<tr><td><strong>MCP 2026-07-28 + OAuth 2.1</strong></td><td>Server MUST be an OAuth 2.1 resource server, MUST implement RFC 9728, MUST validate token audience, MUST NOT pass tokens through. DCR is deprecated in favour of Client ID Metadata Documents.</td><td><span class="sev sev-high">PARTIAL</span> Correct revision, <strong>zero authorization</strong>, and it rejects the two most-deployed revisions.</td></tr>
<tr><td><strong>Export control</strong></td><td>Non-issue <em>if</em> crypto is standard. Since 2021 the ECCN 5D002 BIS/NSA notification applies only to <strong>non-standard cryptography</strong>.</td><td><span class="sev sev-low">CHECK</span> Ed25519/SHA-256 are standard. Verify nothing novel crept into the evidence layer.</td></tr>
</tbody></table></div>
<div class="good"><div class="calltitle">And the one everybody wastes months on</div>
{para("**Do not chase SOC 2 Type II.** It attests a *service organization*. A self-hosted OSS component has no "
      "service to attest, and the tooling is built for cloud-hosted companies. Saying that confidently &mdash; then "
      "handing over signed releases, an SBOM, a disclosure policy and a completed CSA AI-CAIQ &mdash; is a stronger "
      "answer than a certification that does not fit. It becomes a real gate only if you ever operate a hosted "
      "control plane or evidence store.")}</div>
<h3>The pilot bar, and the base rates you are fighting</h3>
{bullets([
 "**IDC/Lenovo: 88% of AI agent PoCs never reach broad production** &mdash; for every 33 pilots, four go live. "
 "Attributed to organisational readiness in data, process and infrastructure, **not model quality**. [EXTERNAL]",
 "**Gartner: over 40% of agentic AI projects cancelled by end-2027** &mdash; escalating cost, unclear business value, "
 "or **inadequate risk controls**. Note what is *not* on that list: technical capability. [EXTERNAL]",
 "**Phase 1 must be observe-only.** For an authority and containment substrate, the difference between a pilot and an "
 "outage is a mode that emits decisions without blocking. One false-positive block in a business-critical flow ends "
 "the pilot.",
 "**Latency is the make-or-break number.** Microsoft claims &lt;0.1&nbsp;ms p99 for the same interception point. "
 "AumOS has **eleven published latency budgets and zero benchmarks**. Silence is read as slow.",
 "**Sign-off is three signatures**: the engineering sponsor, the security architecture review board, and &mdash; in a "
 "regulated firm &mdash; model risk or internal audit. Legal/procurement runs in parallel.",
 "**The expensive failure mode** is the security review starting *after* the technical pilot succeeds, and a missing "
 "SBOM or unsigned release killing a deal that had already won on merit.",
])}
</section>"""


def sec_components():
    chips = filter_bar("comp", [("keep", [("keep", "KEEP"), ("thin", "THIN"), ("cut", "CUT")])],
                       "Search components…")
    rows = ""
    for c in COMPONENTS:
        badge = {"KEEP": "grade-a", "THIN": "grade-c", "CUT": "grade-f"}[c["keep"]]
        rows += (
            f'<details class="dos" data-facets="keep:{c["keep"].lower()}" '
            f'data-text="{esc(c["cid"] + " " + c["name"] + " " + c["verdict"])}">'
            f'<summary><span class="did">{esc(c["cid"])}</span>'
            f'<span class="dname">{esc(c["name"])}<span class="dpath">{esc(c["lang"])}</span></span>'
            f'<span class="grade {badge}">{c["keep"]}</span></summary>'
            f'<div class="body">'
            f'<h4>Value to the OSS / developer community</h4><p>{c["oss"]}</p>'
            f'<h4>Value to an enterprise buyer</h4><p>{c["ent"]}</p>'
            f'<div class="{"good" if c["keep"]=="KEEP" else "warn" if c["keep"]=="THIN" else "danger"}">'
            f'<div class="calltitle">Verdict</div><p>{c["verdict"]}</p></div>'
            f'</div></details>')
    return f"""
<section id="components">
<div class="eyebrow">03 &middot; Portfolio</div>
<h2>Which components create exponential value, and which are borrowed time</h2>
{para("You asked for the honest verdict rather than the best available framing, so that is what this is. A component "
      "earns KEEP only if it does something a developer or an enterprise cannot get more cheaply elsewhere. The test "
      "is not &ldquo;is this good code&rdquo; &mdash; several CUT components are good code. The test is whether a "
      "security architect, asked why you built it instead of adopting the incumbent, would accept the answer.")}
<div class="note">{para("Shown here are the components where the verdict is decisive in either direction. The full "
                        "54-entry treatment is in the "
                        "[critical analysis](aumos-critical-analysis-2026-08-09.html). Roughly 35&ndash;40 of the "
                        "original 54 are commodity; this is the spine that survives the cut to ~25 plus the clearest "
                        "deletions.")}</div>
<div data-filter-scope="components">{chips}{rows}</div>
<div class="warn"><div class="calltitle">The pattern worth naming</div>
{para("Every CUT component fails the same way: it reimplements something a well-funded incumbent gives away, and the "
      "reimplementation is a fraction as complete. Every KEEP component either (a) does something genuinely nobody "
      "does &mdash; P8, P12, composite attestation &mdash; or (b) is *unusually careful systems code* whose value is "
      "the care itself, like `gguf-ext` and `sandbox-runtime`. **Nothing in the middle survives contact with a buyer.**")}</div>
</section>"""


def sec_surface():
    return f"""
<section id="surface">
<div class="eyebrow">04 &middot; Capability surface</div>
<h2>What else the portfolio can credibly offer beyond the four use cases</h2>
{para("You asked what else these components can provide. Each of these is reachable from work that already exists, "
      "and each maps to a buyer who is not currently in your four use cases. They are ordered by distance from what "
      "is already built.")}
<div class="two">
<div class="card"><h4>1. Model-file safety as a standalone product</h4>
{para("`gguf-ext` already does bounded parsing with fuzz targets against a format with a live CVSS 9.8 CVE. Every "
      "team that loads community model files has this exposure and no safe option. **Shippable as an independent "
      "crate/CLI in weeks**, with its own audience, and it needs none of the rest of the stack.")}</div>
<div class="card"><h4>2. Grader attestation for AI evaluation vendors</h4>
{para("Nobody pins the grader. Eval platforms, benchmark maintainers and AI-assurance firms all have the same "
      "credibility problem: the entity producing the evidence is the entity being evaluated. A signed judge-and-corpus "
      "attestation is a **product for the eval ecosystem itself**, not just for end users.")}</div>
<div class="card"><h4>3. Sovereign evidence retention</h4>
{para("CERT-In requires **180 days of ICT logs held inside Indian jurisdiction**; DPDP adds a one-year processing-log "
      "requirement. An evidence plane that is portable, air-gappable and residency-aware is a compliance product for "
      "India and the Gulf that a US-hosted control plane structurally cannot match.")}</div>
<div class="card"><h4>4. Agent incident exchange for CERTs and ISACs</h4>
{para("CERT-In Annexure I item (xx) already makes attacks on AI/ML systems reportable **within 6 hours**. Nobody has "
      "tooling that produces that report. OCSF 1.9 shipped the `ai_agent` and `delegation` objects to carry it. This "
      "is a narrow, unglamorous, genuinely unserved need.")}</div>
<div class="card"><h4>5. Differential-privacy accounting as a service</h4>
{para("`dp-crate` is the best-tested package in the repo. DP accounting appears in RBI FREE-AI and DPDP "
      "conversations, and most teams implement it wrong. A correct, provable accountant with published proofs is "
      "defensible on its own.")}</div>
<div class="card"><h4>6. Conformance-as-a-service for the protocol suite</h4>
{para("The conformance runner now executes **220 verifications across four languages** and is genuinely fail-closed. "
      "If P8 or P12 gain any adoption, the conformance suite becomes the neutral arbiter &mdash; which is how "
      "standards bodies fund themselves and how a specification becomes load-bearing rather than aspirational.")}</div>
</div>
<div class="note"><div class="calltitle">The through-line</div>
{para("Five of those six are **evidence products, not enforcement products**. That is not a coincidence &mdash; it "
      "is the same conclusion the competitive analysis reaches from the other direction. The portfolio's centre of "
      "gravity should move from *stopping agents* to *proving what agents did*, because the first is commodity and "
      "the second is not.")}</div>
</section>"""


def sec_devblockers():
    return f"""
<section id="devblockers">
<div class="eyebrow">05 &middot; Developer adoption</div>
<h2>Why a developer cannot start today &mdash; seven concrete blockers</h2>
{para("These are ordered by how early a developer hits them. The first three are fatal within sixty seconds of "
      "arriving, and none of them is about code quality.")}
{bullets([
 "**Nothing is published.** All four npm packages 404. There is no PyPI project, no crate, no container image, no "
 "release binary. A developer's first action &mdash; `npm install` or `pip install` &mdash; fails. Everything else on "
 "this list is downstream of that. [EXECUTED]",
 "**There is no git remote.** The repository has never been pushed, so there is no README to land on, no issues, no "
 "stars, no releases page. It is invisible.",
 "**The documented run command is a silent no-op.** `npx aumos-mcp --standalone` prints nothing and exits 0 on every "
 "platform, because the main-module check compares an npm symlink against a resolved realpath. The one command in the "
 "README produces silence. [EXECUTED]",
 "**There is no SDK.** For Claude Agent SDK, OpenAI Agents SDK, LangGraph, CrewAI, Pydantic AI or Vercel AI SDK there "
 "is no adapter, no middleware, no hook, no example. The core question &mdash; *how do I wrap my existing agent loop?* "
 "&mdash; has no answer in the repository. `aumos_langchain` is the single genuine adapter and it is not even a "
 "catalogued component.",
 "**The README's copy-paste config is dead on arrival.** It ships `\"command\": \"npx\", \"args\": [\"-y\", "
 "\"@muveraai/aumos-mcp-server\"]` &mdash; a 404 &mdash; and sets `AUMOS_MODE: standalone`, which is the mode that "
 "returns hardcoded security *passes*. A developer who gets past the registry error lands on a control plane that "
 "always says yes.",
 "**Two competing namespaces.** `@aumos/*` and `@muveraai/*` both appear in the tree, and the MCP server and gateway "
 "are split across them. Resolved by the move to `warrantor`, but it must actually be executed.",
 "**No trust signals.** No audit, no fuzzing badge, no provenance attestation, no maintainer roster, no release "
 "cadence, no reference user. A developer evaluating a *security* library checks these before reading a line of code.",
])}
<div class="danger"><div class="calltitle">The blunt version</div>
{para("The repository contains 287 passing Rust tests, 227 TypeScript tests, a four-language conformance suite at "
      "220/220, and genuinely excellent parser work &mdash; **and a developer cannot execute a single line of it.** "
      "The gap between engineering quality and adoption readiness is the largest single finding in this document, and "
      "it is entirely fixable with work that requires no cleverness at all.")}</div>
</section>"""
