//! # aumos-api
//!
//! Generated AumOS API types — the Rust view of the contract plane (`proto/`).
//! Regenerate with `buf generate` from the repo root. CI rejects uncommitted generated code.
//!
//! This crate is the single source of truth for wire types in Rust. Every Wave-1 crate
//! (`aumos-trust-core`, `aumos-eval-guard`, `aumos-kill-switch`, `aumos-credential-vault`,
//! `aumos-nvtrust-bridge`, `defstack-cli`) depends on this crate instead of redefining types
//! (per docs/cross-cutting/19-inter-component-protocol.md §10).

#![forbid(unsafe_code)]

/// Generated identity types (`aumos.identity.v1`).
pub mod identity {
    /// Generated by prost from `proto/aumos/identity/v1/agent.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/aumos.identity.v1.rs"));
    }
}

/// Generated trust types (`aumos.trust.v1`).
pub mod trust {
    /// Generated by prost from `proto/aumos/trust/v1/signing.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/aumos.trust.v1.rs"));
    }
}

/// Generated attestation types (`aumos.attestation.v1`).
pub mod attestation {
    /// Generated by prost from `proto/aumos/attestation/v1/report.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/aumos.attestation.v1.rs"));
    }
}

/// Generated protocol types (`aumos.protocols.v1`).
pub mod protocols {
    /// Generated by prost from `proto/aumos/protocols/v1/*.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/aumos.protocols.v1.rs"));
    }
}
