//! Interop producer: emit the authority-arithmetic vectors `WarrantBounds::contains` decides, so
//! the Python bound proposer's mirror of that arithmetic can be checked against the real one.
//!
//! Usage: `cargo run -p warrantor-warrant --example emit_bounds_vectors -- <output-path>`
//!
//! Why this exists. `python/warrantor_ml/src/warrantor_ml/tasks/bounds.py` re-implements
//! `WarrantBounds::contains` in order to score model 5, the bound proposer, on over-grant rate. A
//! second implementation of authority arithmetic is a second implementation that can disagree with
//! the first — and the four rules it has to mirror are exactly the four that are easy to invert:
//!
//! * `staged_classes`: a SMALLER set is an EXPANSION, because a child staging fewer classes
//!   performs immediately what the parent deferred.
//! * `expires_at`: a child may not outlive its parent.
//! * an absent `budget_cents_observed` is a ceiling of ZERO, never "unlimited".
//! * dropping a DECLARED ceiling is not a narrowing, because an absent budget is never
//!   `SpendLedger::exhausted` and so trades a start-gated budget for an ungated one.
//!
//! Rust decides here; Python must agree. The fixture is regenerated by
//! `tools/ci/run_python_checks.py` before every test run, and the Python side asserts rather than
//! skips when it is present — an interop test that skips silently is a safety net that reports
//! success without being exercised.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::PathBuf;

use warrantor_warrant::{SideEffectClass, WarrantBounds};

/// One named case: a parent, a child, and whatever `contains` decides about them.
struct Case {
    name: &'static str,
    /// What the rule under test is, in the terms the Python mirror has to reproduce.
    rule: &'static str,
    parent: WarrantBounds,
    child: WarrantBounds,
}

fn set(items: &[&str]) -> BTreeSet<String> {
    items.iter().map(|item| (*item).to_string()).collect()
}

fn classes(items: &[SideEffectClass]) -> BTreeSet<SideEffectClass> {
    items.iter().copied().collect()
}

/// A permissive-but-finite parent every case narrows from, so each case varies one axis only.
fn parent_bounds() -> WarrantBounds {
    WarrantBounds {
        tools: set(&["git", "cargo", "rg"]),
        write_paths: set(&["src/**", "tests/**"]),
        egress_hosts: set(&["crates.io", "github.com"]),
        staged_classes: classes(&[SideEffectClass::Financial, SideEffectClass::Destructive]),
        expires_at: 2_000_000_000,
        budget_cents_observed: Some(500),
        delegation_depth: 3,
    }
}

fn cases() -> Vec<Case> {
    let base_child = || WarrantBounds {
        tools: set(&["git"]),
        write_paths: set(&["src/**"]),
        egress_hosts: set(&["crates.io"]),
        staged_classes: classes(&[SideEffectClass::Financial, SideEffectClass::Destructive]),
        expires_at: 1_900_000_000,
        budget_cents_observed: Some(100),
        delegation_depth: 2,
    };

    vec![
        Case {
            name: "contained_narrower_on_every_axis",
            rule: "the baseline: a child that shrinks every set and every ceiling is contained",
            parent: parent_bounds(),
            child: base_child(),
        },
        Case {
            name: "tool_not_held_by_parent",
            rule: "tools: the child's set must be a subset",
            parent: parent_bounds(),
            child: WarrantBounds {
                tools: set(&["git", "curl"]),
                ..base_child()
            },
        },
        Case {
            name: "write_path_not_held_by_parent",
            rule: "write_paths: the child's set must be a subset",
            parent: parent_bounds(),
            child: WarrantBounds {
                write_paths: set(&["src/**", "/etc/**"]),
                ..base_child()
            },
        },
        Case {
            name: "egress_host_not_held_by_parent",
            rule: "egress_hosts: the child's set must be a subset",
            parent: parent_bounds(),
            child: WarrantBounds {
                egress_hosts: set(&["crates.io", "evil.example"]),
                ..base_child()
            },
        },
        Case {
            name: "staged_classes_narrowed_is_an_expansion",
            rule: "staged_classes: a SMALLER set is an EXPANSION — the reversal most likely to \
                   be lost in a Python mirror written from 'smaller means narrower'",
            parent: parent_bounds(),
            child: WarrantBounds {
                staged_classes: classes(&[SideEffectClass::Financial]),
                ..base_child()
            },
        },
        Case {
            name: "staged_classes_widened_is_a_narrowing",
            rule: "staged_classes: staging MORE classes defers more, so it is contained",
            parent: parent_bounds(),
            child: WarrantBounds {
                staged_classes: classes(&[
                    SideEffectClass::Financial,
                    SideEffectClass::Destructive,
                    SideEffectClass::Physical,
                ]),
                ..base_child()
            },
        },
        Case {
            name: "child_outlives_parent",
            rule: "expires_at: a child may not outlive its parent",
            parent: parent_bounds(),
            child: WarrantBounds {
                expires_at: 2_100_000_000,
                ..base_child()
            },
        },
        Case {
            name: "budget_above_parent_ceiling",
            rule: "budget: a higher declared ceiling is an expansion",
            parent: parent_bounds(),
            child: WarrantBounds {
                budget_cents_observed: Some(900),
                ..base_child()
            },
        },
        Case {
            name: "child_drops_a_declared_ceiling",
            rule: "budget: dropping a DECLARED ceiling is an expansion, not a narrowing — an \
                   absent budget is never exhausted, so it is never inherited",
            parent: parent_bounds(),
            child: WarrantBounds {
                budget_cents_observed: None,
                ..base_child()
            },
        },
        Case {
            name: "absent_parent_budget_is_a_ceiling_of_zero",
            rule: "budget: a parent that declares no budget has a ceiling of ZERO and can \
                   delegate nothing, so any positive child ceiling expands",
            parent: WarrantBounds {
                budget_cents_observed: None,
                ..parent_bounds()
            },
            child: WarrantBounds {
                budget_cents_observed: Some(1),
                ..base_child()
            },
        },
        Case {
            name: "absent_on_both_sides_is_contained",
            rule: "budget: zero delegated to zero is a narrowing of nothing, and holds",
            parent: WarrantBounds {
                budget_cents_observed: None,
                ..parent_bounds()
            },
            child: WarrantBounds {
                budget_cents_observed: None,
                ..base_child()
            },
        },
        Case {
            name: "delegation_depth_not_strictly_below",
            rule: "delegation_depth: the child must be STRICTLY below the parent, so equal fails",
            parent: parent_bounds(),
            child: WarrantBounds {
                delegation_depth: 3,
                ..base_child()
            },
        },
    ]
}

fn bounds_json(bounds: &WarrantBounds) -> serde_json::Value {
    serde_json::to_value(bounds).expect("WarrantBounds serialises")
}

fn main() {
    let target: PathBuf = env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(".bounds_interop.json"));

    let vectors: Vec<serde_json::Value> = cases()
        .into_iter()
        .map(|case| {
            // The verdict is decided HERE, by the real implementation, and carried to Python as
            // data. Python never re-derives it from a description of the rule.
            let outcome = case.parent.contains(&case.child);
            serde_json::json!({
                "name": case.name,
                "rule": case.rule,
                "parent": bounds_json(&case.parent),
                "child": bounds_json(&case.child),
                "contained": outcome.is_ok(),
                "error": outcome.err().map(|error| error.to_string()),
            })
        })
        .collect();

    let document = serde_json::json!({
        "format": "warrantor.bounds-interop/1",
        "produced_by": "rust/warrant/examples/emit_bounds_vectors.rs",
        "note": "Rust decides; the Python mirror in warrantor_ml.tasks.bounds must agree on every \
                 vector. A disagreement means two implementations of authority arithmetic have \
                 drifted, and the over-grant rate the bound proposer is scored on is measuring \
                 the wrong thing.",
        "vectors": vectors,
    });

    if let Some(parent) = target.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).expect("create output directory");
        }
    }
    fs::write(
        &target,
        serde_json::to_string_pretty(&document).expect("serialise interop document"),
    )
    .expect("write interop document");
    println!(
        "wrote {} vectors to {}",
        document["vectors"].as_array().map_or(0, Vec::len),
        target.display()
    );
}
