// Generates src/generated.ts from the repository's actual state.
//
// Everything the Worker serves is derived here rather than hand-maintained, so a
// new Go module or protocol schema cannot silently go unserved: `npm run check`
// regenerates and diffs, and CI fails if the committed file is stale.

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..', '..');

/** Go modules: directory under go/ -> declared module path. */
function goModules() {
  const goDir = join(repoRoot, 'go');
  const out = {};
  for (const entry of readdirSync(goDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    let modLine;
    try {
      modLine = readFileSync(join(goDir, entry.name, 'go.mod'), 'utf8').split('\n')[0];
    } catch {
      continue; // not a module
    }
    const path = modLine.replace(/^module\s+/, '').trim();
    if (!path.startsWith('muveraai.com/go/')) {
      throw new Error(`go/${entry.name}: module path ${path} is not under muveraai.com/go/`);
    }
    // The subdirectory Go must check out, relative to the repository root.
    out[path.slice('muveraai.com/go/'.length)] = { modulePath: path, subDir: `go/${entry.name}` };
  }
  return out;
}

/** Protocol schemas: $id path -> schema body. Keyed by the URL the $id declares. */
function schemas() {
  const specDir = join(repoRoot, 'specs', 'protocols');
  const out = {};
  for (const file of readdirSync(specDir)) {
    if (!file.endsWith('.schema.json')) continue;
    const body = readFileSync(join(specDir, file), 'utf8');
    const parsed = JSON.parse(body);
    const id = parsed.$id;
    if (typeof id !== 'string') throw new Error(`${file}: missing $id`);
    const prefix = 'https://muveraai.com/schemas/';
    if (!id.startsWith(prefix)) throw new Error(`${file}: $id ${id} is not under ${prefix}`);
    // Serve the exact bytes on disk so the served document and the committed
    // artifact are byte-identical -- a hash of either is a hash of both.
    out[id.slice(prefix.length)] = body;
  }
  return out;
}

const mods = goModules();
const schemaMap = schemas();

const banner = `// GENERATED by scripts/generate.mjs -- do not edit.
// Run \`npm run generate\` after adding a Go module or protocol schema.
`;

const body = `${banner}
export interface GoModule {
  readonly modulePath: string;
  readonly subDir: string;
}

export const REPO_URL = 'https://github.com/MuVeraAI/aumos';

export const GO_MODULES: Readonly<Record<string, GoModule>> = ${JSON.stringify(mods, null, 2)};

export const SCHEMAS: Readonly<Record<string, string>> = ${JSON.stringify(schemaMap, null, 2)};
`;

mkdirSync(join(here, '..', 'src'), { recursive: true });
writeFileSync(join(here, '..', 'src', 'generated.ts'), body, 'utf8');

console.log(`generated: ${Object.keys(mods).length} go modules, ${Object.keys(schemaMap).length} schemas`);
