"""Generated by tools/protocols/generate.py; do not edit."""

from __future__ import annotations

from typing import Generic, Literal, TypeAlias, TypeVar, TypedDict

JsonScalar: TypeAlias = str | int | bool | None
JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]
ProtocolId: TypeAlias = Literal["P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10", "P11", "P12"]
PayloadT = TypeVar("PayloadT")

class Signature(TypedDict):
    algorithm: Literal["Ed25519"]
    key_id: str
    value: str

class ArtifactReference(TypedDict):
    uri: str
    digest: str
    media_type: str
    version: str
    license: str

class Budget(TypedDict):
    steps: int
    wall_clock_seconds: int
    tokens: int
    money_minor: int
    external_calls: int
    data_bytes: int
    irreversible_actions: int

class PolicyDecision(TypedDict):
    engine: Literal["opa", "cedar", "openshell"]
    decision: Literal["allow", "deny"]
    policy_digest: str
    matched_rules: list[str]

class DeterministicCheck(TypedDict):
    name: str
    passed: bool
    detail_digest: str

class Transformation(TypedDict):
    operation: str
    implementation: str
    input_digest: str
    output_digest: str
    applied_at: int

class EvaluationAssertion(TypedDict):
    name: str
    expected_digest: str
    actual_digest: str
    passed: bool

class NetworkPolicy(TypedDict):
    egress_default: Literal["deny", "allow"]
    allowlist: list[str]
    blocklist: list[str]
    dns_policy: Literal["deny", "allowlisted"]

class AgentAuthorityEnvelopePayload(TypedDict):
    subject: str
    purpose: str
    resources: list[str]
    tools: list[str]
    data_classes: list[Literal["L0", "L1", "L2", "L3", "L4"]]
    side_effect_class: Literal["read", "write", "financial", "destructive", "physical"]
    budget: Budget
    geographies: list[str]
    delegation_depth: int
    approvals: list[str]
    revocation_handle: str

class AgentActionReceiptPayload(TypedDict):
    phase: Literal["precommit", "final"]
    actor: str
    authority_digest: str
    artifact_digests: list[str]
    context_digest: str
    policy_decision: PolicyDecision
    operation: str
    checks: list[DeterministicCheck]
    approvers: list[str]
    outcome: Literal["pending", "committed", "rolled_back", "failed"]
    rollback_pointer: str
    parent_receipt: str

class ContextProvenanceEnvelopePayload(TypedDict):
    source_identity: str
    acquired_at: int
    consent: bool
    sensitivity: Literal["L0", "L1", "L2", "L3", "L4"]
    content_digest: str
    confidence_micros: int
    transformations: list[Transformation]
    derived_from: list[str]
    taints: list[Literal["untrusted", "pii", "sensitive", "malware"]]
    allowed_uses: list[str]

class AgentMemoryIntegrityRecordPayload(TypedDict):
    sequence: int
    previous_digest: str
    owner: str
    content_digest: str
    confidence_micros: int
    contradiction_links: list[str]
    provenance_digest: str
    quarantine_state: Literal["clean", "quarantined", "resolved"]
    supersedes: str
    retention_until: int
    consent_revoked: bool

class SecureSkillPackagePayload(TypedDict):
    name: str
    package: ArtifactReference
    instructions_digest: str
    code: ArtifactReference
    runtime: Literal["wasm", "python", "node", "container"]
    tools: list[str]
    permissions: list[str]
    publisher_identity: str
    ai_sbom: ArtifactReference
    evaluation_bundle: ArtifactReference
    limitations: list[str]
    revocation_handle: str

class AiArtifactTrustManifestPayload(TypedDict):
    artifacts: list[ArtifactReference]
    roles: list[Literal["model", "dataset", "tokenizer", "prompt", "adapter", "container", "policy", "skill", "evaluation"]]
    root_digest: str
    build_provenance: ArtifactReference
    deployment_attestations: list[ArtifactReference]

class AutonomyBudgetSpecificationPayload(TypedDict):
    budget: Budget
    currency: str
    privilege: Literal["none", "read", "write", "admin"]
    expected_risk_micros: int
    approval_required: bool
    replenishment: Literal["none", "manual", "scheduled"]

class VerifiableEvaluationBundlePayload(TypedDict):
    corpus: ArtifactReference
    environment: ArtifactReference
    model: ArtifactReference
    harness: ArtifactReference
    policy: ArtifactReference
    seeds: list[int]
    trace_digests: list[str]
    judge: ArtifactReference
    assertions: list[EvaluationAssertion]
    passed_count: int
    failed_count: int

class AgentIncidentExchangePayload(TypedDict):
    incident_type: Literal["goal_hijack", "memory_poisoning", "tool_abuse", "identity_compromise", "exfiltration", "rogue_delegation"]
    severity: Literal["info", "low", "medium", "high", "critical"]
    agent: str
    authority_digest: str
    evidence_refs: list[str]
    mitre_atlas_ids: list[str]
    ocsf_class_uid: int
    detected_at: int
    contained_at: int
    containment_status: Literal["open", "contained", "eradicated", "recovered"]

class MultiAgentDelegationExchangePayload(TypedDict):
    delegator: str
    delegatee: str
    parent_authority_digest: str
    delegation_chain: list[str]
    hop_count: int
    max_depth: int
    capabilities: list[str]
    parent_budget: Budget
    delegated_budget: Budget
    quorum: int
    approvals: list[str]
    evidence_requirements: list[str]
    result_digest: str
    status: Literal["offered", "accepted", "completed", "rejected", "revoked"]

class ProofCarryingRemediationBundlePayload(TypedDict):
    reproducer: ArtifactReference
    root_cause_digest: str
    affected_versions: list[str]
    patch: ArtifactReference
    tests: list[ArtifactReference]
    regression_evidence: ArtifactReference
    build_provenance: ArtifactReference
    embargo_until: int
    disclosure_status: Literal["embargoed", "coordinated", "public"]

class CapabilityAttestationProfilePayload(TypedDict):
    subject: str
    runtime: str
    tools: list[str]
    policy_digest: str
    credential_types: list[str]
    network: NetworkPolicy
    memory_isolation: Literal["process", "container", "wasm", "tee"]
    model: ArtifactReference
    sandbox: Literal["wasm", "container", "tee"]
    attestation_evidence: ArtifactReference
    valid_until: int

class ProtocolEnvelope(TypedDict, Generic[PayloadT]):
    protocol: ProtocolId
    version: Literal["1.0.0"]
    message_id: str
    issuer: str
    issued_at: int
    expires_at: int
    nonce: str
    payload: PayloadT
    critical_extensions: list[str]
    extensions: dict[str, JsonValue]
    signature: Signature

AgentAuthorityEnvelope: TypeAlias = ProtocolEnvelope[AgentAuthorityEnvelopePayload]
AgentActionReceipt: TypeAlias = ProtocolEnvelope[AgentActionReceiptPayload]
ContextProvenanceEnvelope: TypeAlias = ProtocolEnvelope[ContextProvenanceEnvelopePayload]
AgentMemoryIntegrityRecord: TypeAlias = ProtocolEnvelope[AgentMemoryIntegrityRecordPayload]
SecureSkillPackage: TypeAlias = ProtocolEnvelope[SecureSkillPackagePayload]
AiArtifactTrustManifest: TypeAlias = ProtocolEnvelope[AiArtifactTrustManifestPayload]
AutonomyBudgetSpecification: TypeAlias = ProtocolEnvelope[AutonomyBudgetSpecificationPayload]
VerifiableEvaluationBundle: TypeAlias = ProtocolEnvelope[VerifiableEvaluationBundlePayload]
AgentIncidentExchange: TypeAlias = ProtocolEnvelope[AgentIncidentExchangePayload]
MultiAgentDelegationExchange: TypeAlias = ProtocolEnvelope[MultiAgentDelegationExchangePayload]
ProofCarryingRemediationBundle: TypeAlias = ProtocolEnvelope[ProofCarryingRemediationBundlePayload]
CapabilityAttestationProfile: TypeAlias = ProtocolEnvelope[CapabilityAttestationProfilePayload]
