//! Generated by tools/protocols/generate.py; do not edit.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProtocolEnvelope<Payload> {
    pub protocol: String,
    pub version: String,
    pub message_id: String,
    pub issuer: String,
    pub issued_at: u64,
    pub expires_at: u64,
    pub nonce: String,
    pub payload: Payload,
    pub critical_extensions: Vec<String>,
    pub extensions: BTreeMap<String, serde_json::Value>,
    pub signature: Signature,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Signature {
    pub algorithm: String,
    pub key_id: String,
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactReference {
    pub uri: String,
    pub digest: String,
    pub media_type: String,
    pub version: String,
    pub license: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Budget {
    pub steps: u64,
    pub wall_clock_seconds: u64,
    pub tokens: u64,
    pub money_minor: u64,
    pub external_calls: u64,
    pub data_bytes: u64,
    pub irreversible_actions: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PolicyDecision {
    pub engine: String,
    pub decision: String,
    pub policy_digest: String,
    pub matched_rules: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeterministicCheck {
    pub name: String,
    pub passed: bool,
    pub detail_digest: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Transformation {
    pub operation: String,
    pub implementation: String,
    pub input_digest: String,
    pub output_digest: String,
    pub applied_at: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvaluationAssertion {
    pub name: String,
    pub expected_digest: String,
    pub actual_digest: String,
    pub passed: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkPolicy {
    pub egress_default: String,
    pub allowlist: Vec<String>,
    pub blocklist: Vec<String>,
    pub dns_policy: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentAuthorityEnvelopePayload {
    pub subject: String,
    pub purpose: String,
    pub resources: Vec<String>,
    pub tools: Vec<String>,
    pub data_classes: Vec<String>,
    pub side_effect_class: String,
    pub budget: Budget,
    pub geographies: Vec<String>,
    pub delegation_depth: u64,
    pub approvals: Vec<String>,
    pub revocation_handle: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentActionReceiptPayload {
    pub phase: String,
    pub actor: String,
    pub authority_digest: String,
    pub artifact_digests: Vec<String>,
    pub context_digest: String,
    pub policy_decision: PolicyDecision,
    pub operation: String,
    pub checks: Vec<DeterministicCheck>,
    pub approvers: Vec<String>,
    pub outcome: String,
    pub rollback_pointer: String,
    pub parent_receipt: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ContextProvenanceEnvelopePayload {
    pub source_identity: String,
    pub acquired_at: u64,
    pub consent: bool,
    pub sensitivity: String,
    pub content_digest: String,
    pub confidence_micros: u64,
    pub transformations: Vec<Transformation>,
    pub derived_from: Vec<String>,
    pub taints: Vec<String>,
    pub allowed_uses: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentMemoryIntegrityRecordPayload {
    pub sequence: u64,
    pub previous_digest: String,
    pub owner: String,
    pub content_digest: String,
    pub confidence_micros: u64,
    pub contradiction_links: Vec<String>,
    pub provenance_digest: String,
    pub quarantine_state: String,
    pub supersedes: String,
    pub retention_until: u64,
    pub consent_revoked: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SecureSkillPackagePayload {
    pub name: String,
    pub package: ArtifactReference,
    pub instructions_digest: String,
    pub code: ArtifactReference,
    pub runtime: String,
    pub tools: Vec<String>,
    pub permissions: Vec<String>,
    pub publisher_identity: String,
    pub ai_sbom: ArtifactReference,
    pub evaluation_bundle: ArtifactReference,
    pub limitations: Vec<String>,
    pub revocation_handle: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AiArtifactTrustManifestPayload {
    pub artifacts: Vec<ArtifactReference>,
    pub roles: Vec<String>,
    pub root_digest: String,
    pub build_provenance: ArtifactReference,
    pub deployment_attestations: Vec<ArtifactReference>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AutonomyBudgetSpecificationPayload {
    pub budget: Budget,
    pub currency: String,
    pub privilege: String,
    pub expected_risk_micros: u64,
    pub approval_required: bool,
    pub replenishment: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerifiableEvaluationBundlePayload {
    pub corpus: ArtifactReference,
    pub environment: ArtifactReference,
    pub model: ArtifactReference,
    pub harness: ArtifactReference,
    pub policy: ArtifactReference,
    pub seeds: Vec<u64>,
    pub trace_digests: Vec<String>,
    pub judge: ArtifactReference,
    pub assertions: Vec<EvaluationAssertion>,
    pub passed_count: u64,
    pub failed_count: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentIncidentExchangePayload {
    pub incident_type: String,
    pub severity: String,
    pub agent: String,
    pub authority_digest: String,
    pub evidence_refs: Vec<String>,
    pub mitre_atlas_ids: Vec<String>,
    pub ocsf_class_uid: u64,
    pub detected_at: u64,
    pub contained_at: u64,
    pub containment_status: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MultiAgentDelegationExchangePayload {
    pub delegator: String,
    pub delegatee: String,
    pub parent_authority_digest: String,
    pub delegation_chain: Vec<String>,
    pub hop_count: u64,
    pub max_depth: u64,
    pub capabilities: Vec<String>,
    pub parent_budget: Budget,
    pub delegated_budget: Budget,
    pub quorum: u64,
    pub approvals: Vec<String>,
    pub evidence_requirements: Vec<String>,
    pub result_digest: String,
    pub status: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProofCarryingRemediationBundlePayload {
    pub reproducer: ArtifactReference,
    pub root_cause_digest: String,
    pub affected_versions: Vec<String>,
    pub patch: ArtifactReference,
    pub tests: Vec<ArtifactReference>,
    pub regression_evidence: ArtifactReference,
    pub build_provenance: ArtifactReference,
    pub embargo_until: u64,
    pub disclosure_status: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CapabilityAttestationProfilePayload {
    pub subject: String,
    pub runtime: String,
    pub tools: Vec<String>,
    pub policy_digest: String,
    pub credential_types: Vec<String>,
    pub network: NetworkPolicy,
    pub memory_isolation: String,
    pub model: ArtifactReference,
    pub sandbox: String,
    pub attestation_evidence: ArtifactReference,
    pub valid_until: u64,
}

pub type AgentAuthorityEnvelope = ProtocolEnvelope<AgentAuthorityEnvelopePayload>;
pub type AgentActionReceipt = ProtocolEnvelope<AgentActionReceiptPayload>;
pub type ContextProvenanceEnvelope = ProtocolEnvelope<ContextProvenanceEnvelopePayload>;
pub type AgentMemoryIntegrityRecord = ProtocolEnvelope<AgentMemoryIntegrityRecordPayload>;
pub type SecureSkillPackage = ProtocolEnvelope<SecureSkillPackagePayload>;
pub type AiArtifactTrustManifest = ProtocolEnvelope<AiArtifactTrustManifestPayload>;
pub type AutonomyBudgetSpecification = ProtocolEnvelope<AutonomyBudgetSpecificationPayload>;
pub type VerifiableEvaluationBundle = ProtocolEnvelope<VerifiableEvaluationBundlePayload>;
pub type AgentIncidentExchange = ProtocolEnvelope<AgentIncidentExchangePayload>;
pub type MultiAgentDelegationExchange = ProtocolEnvelope<MultiAgentDelegationExchangePayload>;
pub type ProofCarryingRemediationBundle = ProtocolEnvelope<ProofCarryingRemediationBundlePayload>;
pub type CapabilityAttestationProfile = ProtocolEnvelope<CapabilityAttestationProfilePayload>;
