#!/usr/bin/env bash
# Evaluate one finished T1 arm: fetch the adapter, publish it, score it, pair it.
#
# Every step drives `python -m` with PYTHONPATH rather than the `warrantor-ml-*` console scripts.
# Those scripts are generated by an editable install that points at a DIFFERENT worktree on this
# machine, so calling them would measure another checkout's code. See
# memory/editable-install-points-at-another-worktree.md.
set -euo pipefail

ARM="${1:?usage: evaluate-arm.sh <A|B|C>}"
case "$ARM" in
  A) RUN_ID=T1-A-control-2026-09-01 ;;
  B) RUN_ID=T1-B-attention-2026-09-01 ;;
  C) RUN_ID=T1-C-mlp-2026-09-01 ;;
  *) echo "arm must be A, B or C" >&2; exit 2 ;;
esac

REPO="M:/Project AumOS - Open Secure AI Alliance/aumos"
export PYTHONPATH="$REPO/python/warrantor_ml/src"
export PYTHONIOENCODING=utf-8 PYTHONUTF8=1   # Modal/tqdm emit U+2713; Windows cp1252 dies on it

BASE_SNAPSHOT="M:/hf/hub/models--Qwen--Qwen3Guard-Gen-0.6B/snapshots/fada3b2f655b89601929198343c94cd2f64d93cc"
OLLAMA_BASE="hf.co/mradermacher/Qwen3Guard-Gen-0.6B-GGUF:Q4_K_M"   # the tag the BASELINE was measured on
CONVERTER="C:/Users/MuVeraAICorporation/.unsloth/llama.cpp/convert_lora_to_gguf.py"
BASELINE="$REPO/eval_results/baseline-0.6b-2026-09-01/expguard-2026-09-01.json"
ADAPTER="$REPO/t1-staging/adapters/$RUN_ID"
OUT="$REPO/eval_results/$RUN_ID"

echo "== 1/4 fetch the adapter off the Modal volume"
# The volume path is recipe-qualified (`<recipe_id>@<arm>/<run_id>`), not the bare run id, so it
# is read from the run record rather than reconstructed -- a guessed path fails late and loudly.
RECORD="$REPO/t1-staging/run_record_$RUN_ID.json"
VOL_PATH=$(python -c "import json,sys;print(json.load(open(sys.argv[1]))['adapter_path'])" "$RECORD")
echo "   volume path: $VOL_PATH"
mkdir -p "$(dirname "$ADAPTER")"
[ -d "$ADAPTER" ] || modal volume get warrantor-adapters "$VOL_PATH" "$(dirname "$ADAPTER")/"

echo "== 1b  verify the adapter trained the modules this arm is FOR"
# Read back what was trained rather than trusting what was dispatched. The three arms were
# identical once already, when `lane_export` silently discarded the target-modules override and
# every arm rendered the control -- an experiment that would have bought three copies of one
# result and looked entirely healthy. This refuses before spending an evaluation on it.
python - "$ADAPTER" "$ARM" <<'PY'
import json, sys
from pathlib import Path
EXPECTED = {
    "A": {"q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"},
    "B": {"q_proj", "k_proj", "v_proj", "o_proj"},
    "C": {"gate_proj", "up_proj", "down_proj"},
}
adapter, arm = Path(sys.argv[1]), sys.argv[2]
got = set(json.loads((adapter / "adapter_config.json").read_text())["target_modules"])
want = EXPECTED[arm]
if got != want:
    raise SystemExit(
        f"REFUSING: arm {arm} trained {sorted(got)} but this arm is defined by {sorted(want)}.
"
        "The adapter does not answer the question this arm was dispatched to answer."
    )
print(f"   arm {arm} trained exactly its {len(want)} modules: {sorted(want)}")
PY

echo "== 2/4 convert to GGUF and register with Ollama"
python -m warrantor_ml.publish \
  --adapter "$ADAPTER" --base-snapshot "$BASE_SNAPSHOT" --ollama-base "$OLLAMA_BASE" \
  --recipe-id guard-0.6b-expguard-weak --run-id "$RUN_ID" --converter "$CONVERTER"

echo "== 3/4 score on ExpGuardTest"
# seed/num-ctx pinned to the BASELINE's recorded options (num_ctx 8192, seed 0, greedy). A guard
# verdict is sensitive to context length, so an unpinned run is not comparable to the baseline.
mkdir -p "$OUT"
MODEL="warrantor-guard-0.6b-expguard-weak-$(echo "$RUN_ID" | tr '[:upper:]' '[:lower:]')"
python -m warrantor_ml.benchmark_expguard --backend ollama --model "$MODEL"   --seed 0 --num-ctx 8192 --out "$OUT/expguard-$RUN_ID.json"

echo "== 4/4 pair against the 0.6B baseline (122 controversial)"
python - "$OUT" "$BASELINE" "$RUN_ID" <<'PY'
import sys, glob
from pathlib import Path
from warrantor_ml.paired_analysis import compare, render
cand = sorted(glob.glob(str(Path(sys.argv[1]) / "expguard-*.json")))[-1]
print(render(compare(Path(cand), Path(sys.argv[2]), sys.argv[3])))
PY
