//! # warrantor-api
//!
//! Generated Warrantor API types — the Rust view of the contract plane (`proto/`).
//!
//! These types are generated by `build.rs` (tonic-build) into `OUT_DIR` on **every** `cargo build`
//! and are never committed, which is why there is no regeneration command: the types cannot drift
//! from `proto/` because they do not outlive a build. `buf` is used for `lint` and `breaking` only
//! — it does not generate Rust. See `proto/README.md`.
//!
//! This crate is the single source of truth for wire types in Rust. Every Wave-1 crate
//! (`warrantor-trust-core`, `warrantor-eval-guard`, `warrantor-kill-switch`, `warrantor-credential-vault`,
//! `warrantor-nvtrust-bridge`, `defstack-cli`) depends on this crate instead of redefining types
//! (per docs/cross-cutting/19-inter-component-protocol.md §10).

#![forbid(unsafe_code)]

/// Generated identity types (`warrantor.identity.v1`).
pub mod identity {
    /// Generated by prost from `proto/warrantor/identity/v1/agent.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/warrantor.identity.v1.rs"));
    }
}

/// Generated trust types (`warrantor.trust.v1`).
pub mod trust {
    /// Generated by prost from `proto/warrantor/trust/v1/signing.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/warrantor.trust.v1.rs"));
    }
}

/// Generated attestation types (`warrantor.attestation.v1`).
pub mod attestation {
    /// Generated by prost from `proto/warrantor/attestation/v1/report.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/warrantor.attestation.v1.rs"));
    }
}

/// Generated protocol types (`warrantor.protocols.v1`).
pub mod protocols {
    /// Generated by prost from `proto/warrantor/protocols/v1/*.proto`.
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/warrantor.protocols.v1.rs"));
    }
}
