// Generated by tools/protocols/generate.py; do not edit.
package protocolcontracts

type JSONValue interface{}

type ProtocolEnvelope[Payload any] struct {
	Protocol           string               `json:"protocol"`
	Version            string               `json:"version"`
	MessageID          string               `json:"message_id"`
	Issuer             string               `json:"issuer"`
	IssuedAt           uint64               `json:"issued_at"`
	ExpiresAt          uint64               `json:"expires_at"`
	Nonce              string               `json:"nonce"`
	Payload            Payload              `json:"payload"`
	CriticalExtensions []string             `json:"critical_extensions"`
	Extensions         map[string]JSONValue `json:"extensions"`
	Signature          Signature            `json:"signature"`
}

type Signature struct {
	Algorithm string `json:"algorithm"`
	KeyId     string `json:"key_id"`
	Value     string `json:"value"`
}

type ArtifactReference struct {
	Uri       string `json:"uri"`
	Digest    string `json:"digest"`
	MediaType string `json:"media_type"`
	Version   string `json:"version"`
	License   string `json:"license"`
}

type Budget struct {
	Steps               uint64 `json:"steps"`
	WallClockSeconds    uint64 `json:"wall_clock_seconds"`
	Tokens              uint64 `json:"tokens"`
	MoneyMinor          uint64 `json:"money_minor"`
	ExternalCalls       uint64 `json:"external_calls"`
	DataBytes           uint64 `json:"data_bytes"`
	IrreversibleActions uint64 `json:"irreversible_actions"`
}

type PolicyDecision struct {
	Engine       string   `json:"engine"`
	Decision     string   `json:"decision"`
	PolicyDigest string   `json:"policy_digest"`
	MatchedRules []string `json:"matched_rules"`
}

type DeterministicCheck struct {
	Name         string `json:"name"`
	Passed       bool   `json:"passed"`
	DetailDigest string `json:"detail_digest"`
}

type Transformation struct {
	Operation      string `json:"operation"`
	Implementation string `json:"implementation"`
	InputDigest    string `json:"input_digest"`
	OutputDigest   string `json:"output_digest"`
	AppliedAt      uint64 `json:"applied_at"`
}

type EvaluationAssertion struct {
	Name           string `json:"name"`
	ExpectedDigest string `json:"expected_digest"`
	ActualDigest   string `json:"actual_digest"`
	Passed         bool   `json:"passed"`
}

type NetworkPolicy struct {
	EgressDefault string   `json:"egress_default"`
	Allowlist     []string `json:"allowlist"`
	Blocklist     []string `json:"blocklist"`
	DnsPolicy     string   `json:"dns_policy"`
}

type AgentAuthorityEnvelopePayload struct {
	Subject          string   `json:"subject"`
	Purpose          string   `json:"purpose"`
	Resources        []string `json:"resources"`
	Tools            []string `json:"tools"`
	DataClasses      []string `json:"data_classes"`
	SideEffectClass  string   `json:"side_effect_class"`
	Budget           Budget   `json:"budget"`
	Geographies      []string `json:"geographies"`
	DelegationDepth  uint64   `json:"delegation_depth"`
	Approvals        []string `json:"approvals"`
	RevocationHandle string   `json:"revocation_handle"`
}

type AgentActionReceiptPayload struct {
	Phase           string               `json:"phase"`
	Actor           string               `json:"actor"`
	AuthorityDigest string               `json:"authority_digest"`
	ArtifactDigests []string             `json:"artifact_digests"`
	ContextDigest   string               `json:"context_digest"`
	PolicyDecision  PolicyDecision       `json:"policy_decision"`
	Operation       string               `json:"operation"`
	Checks          []DeterministicCheck `json:"checks"`
	Approvers       []string             `json:"approvers"`
	Outcome         string               `json:"outcome"`
	RollbackPointer string               `json:"rollback_pointer"`
	ParentReceipt   string               `json:"parent_receipt"`
}

type ContextProvenanceEnvelopePayload struct {
	SourceIdentity   string           `json:"source_identity"`
	AcquiredAt       uint64           `json:"acquired_at"`
	Consent          bool             `json:"consent"`
	Sensitivity      string           `json:"sensitivity"`
	ContentDigest    string           `json:"content_digest"`
	ConfidenceMicros uint64           `json:"confidence_micros"`
	Transformations  []Transformation `json:"transformations"`
	DerivedFrom      []string         `json:"derived_from"`
	Taints           []string         `json:"taints"`
	AllowedUses      []string         `json:"allowed_uses"`
}

type AgentMemoryIntegrityRecordPayload struct {
	Sequence           uint64   `json:"sequence"`
	PreviousDigest     string   `json:"previous_digest"`
	Owner              string   `json:"owner"`
	ContentDigest      string   `json:"content_digest"`
	ConfidenceMicros   uint64   `json:"confidence_micros"`
	ContradictionLinks []string `json:"contradiction_links"`
	ProvenanceDigest   string   `json:"provenance_digest"`
	QuarantineState    string   `json:"quarantine_state"`
	Supersedes         string   `json:"supersedes"`
	RetentionUntil     uint64   `json:"retention_until"`
	ConsentRevoked     bool     `json:"consent_revoked"`
}

type SecureSkillPackagePayload struct {
	Name               string            `json:"name"`
	Package            ArtifactReference `json:"package"`
	InstructionsDigest string            `json:"instructions_digest"`
	Code               ArtifactReference `json:"code"`
	Runtime            string            `json:"runtime"`
	Tools              []string          `json:"tools"`
	Permissions        []string          `json:"permissions"`
	PublisherIdentity  string            `json:"publisher_identity"`
	AiSbom             ArtifactReference `json:"ai_sbom"`
	EvaluationBundle   ArtifactReference `json:"evaluation_bundle"`
	Limitations        []string          `json:"limitations"`
	RevocationHandle   string            `json:"revocation_handle"`
}

type AiArtifactTrustManifestPayload struct {
	Artifacts              []ArtifactReference `json:"artifacts"`
	Roles                  []string            `json:"roles"`
	RootDigest             string              `json:"root_digest"`
	BuildProvenance        ArtifactReference   `json:"build_provenance"`
	DeploymentAttestations []ArtifactReference `json:"deployment_attestations"`
}

type AutonomyBudgetSpecificationPayload struct {
	Budget             Budget `json:"budget"`
	Currency           string `json:"currency"`
	Privilege          string `json:"privilege"`
	ExpectedRiskMicros uint64 `json:"expected_risk_micros"`
	ApprovalRequired   bool   `json:"approval_required"`
	Replenishment      string `json:"replenishment"`
}

type VerifiableEvaluationBundlePayload struct {
	Corpus       ArtifactReference     `json:"corpus"`
	Environment  ArtifactReference     `json:"environment"`
	Model        ArtifactReference     `json:"model"`
	Harness      ArtifactReference     `json:"harness"`
	Policy       ArtifactReference     `json:"policy"`
	Seeds        []uint64              `json:"seeds"`
	TraceDigests []string              `json:"trace_digests"`
	Judge        ArtifactReference     `json:"judge"`
	Assertions   []EvaluationAssertion `json:"assertions"`
	PassedCount  uint64                `json:"passed_count"`
	FailedCount  uint64                `json:"failed_count"`
}

type AgentIncidentExchangePayload struct {
	IncidentType      string   `json:"incident_type"`
	Severity          string   `json:"severity"`
	Agent             string   `json:"agent"`
	AuthorityDigest   string   `json:"authority_digest"`
	EvidenceRefs      []string `json:"evidence_refs"`
	MitreAtlasIds     []string `json:"mitre_atlas_ids"`
	OcsfClassUid      uint64   `json:"ocsf_class_uid"`
	DetectedAt        uint64   `json:"detected_at"`
	ContainedAt       uint64   `json:"contained_at"`
	ContainmentStatus string   `json:"containment_status"`
}

type MultiAgentDelegationExchangePayload struct {
	Delegator             string   `json:"delegator"`
	Delegatee             string   `json:"delegatee"`
	ParentAuthorityDigest string   `json:"parent_authority_digest"`
	DelegationChain       []string `json:"delegation_chain"`
	HopCount              uint64   `json:"hop_count"`
	MaxDepth              uint64   `json:"max_depth"`
	Capabilities          []string `json:"capabilities"`
	ParentBudget          Budget   `json:"parent_budget"`
	DelegatedBudget       Budget   `json:"delegated_budget"`
	Quorum                uint64   `json:"quorum"`
	Approvals             []string `json:"approvals"`
	EvidenceRequirements  []string `json:"evidence_requirements"`
	ResultDigest          string   `json:"result_digest"`
	Status                string   `json:"status"`
}

type ProofCarryingRemediationBundlePayload struct {
	Reproducer         ArtifactReference   `json:"reproducer"`
	RootCauseDigest    string              `json:"root_cause_digest"`
	AffectedVersions   []string            `json:"affected_versions"`
	Patch              ArtifactReference   `json:"patch"`
	Tests              []ArtifactReference `json:"tests"`
	RegressionEvidence ArtifactReference   `json:"regression_evidence"`
	BuildProvenance    ArtifactReference   `json:"build_provenance"`
	EmbargoUntil       uint64              `json:"embargo_until"`
	DisclosureStatus   string              `json:"disclosure_status"`
}

type CapabilityAttestationProfilePayload struct {
	Subject             string            `json:"subject"`
	Runtime             string            `json:"runtime"`
	Tools               []string          `json:"tools"`
	PolicyDigest        string            `json:"policy_digest"`
	CredentialTypes     []string          `json:"credential_types"`
	Network             NetworkPolicy     `json:"network"`
	MemoryIsolation     string            `json:"memory_isolation"`
	Model               ArtifactReference `json:"model"`
	Sandbox             string            `json:"sandbox"`
	AttestationEvidence ArtifactReference `json:"attestation_evidence"`
	ValidUntil          uint64            `json:"valid_until"`
}

type AgentAuthorityEnvelope ProtocolEnvelope[AgentAuthorityEnvelopePayload]
type AgentActionReceipt ProtocolEnvelope[AgentActionReceiptPayload]
type ContextProvenanceEnvelope ProtocolEnvelope[ContextProvenanceEnvelopePayload]
type AgentMemoryIntegrityRecord ProtocolEnvelope[AgentMemoryIntegrityRecordPayload]
type SecureSkillPackage ProtocolEnvelope[SecureSkillPackagePayload]
type AiArtifactTrustManifest ProtocolEnvelope[AiArtifactTrustManifestPayload]
type AutonomyBudgetSpecification ProtocolEnvelope[AutonomyBudgetSpecificationPayload]
type VerifiableEvaluationBundle ProtocolEnvelope[VerifiableEvaluationBundlePayload]
type AgentIncidentExchange ProtocolEnvelope[AgentIncidentExchangePayload]
type MultiAgentDelegationExchange ProtocolEnvelope[MultiAgentDelegationExchangePayload]
type ProofCarryingRemediationBundle ProtocolEnvelope[ProofCarryingRemediationBundlePayload]
type CapabilityAttestationProfile ProtocolEnvelope[CapabilityAttestationProfilePayload]
