"""warrantor-harness CLI."""

from __future__ import annotations

import argparse
import json
import sys

from warrantor_harness import AgentType, HarnessConfig, SideEffectClass, secure_session


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="warrantor-harness", description="Run a coding agent in a secured Warrantor session."
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    run_p = sub.add_parser("run", help="Run a command in a secured session.")
    run_p.add_argument(
        "--agent", choices=[a.value for a in AgentType], default=AgentType.GENERIC.value
    )
    run_p.add_argument("--dir", default=".", help="Working directory.")
    run_p.add_argument(
        "--tools", default="git,npm,cargo,python,go,make", help="Comma-separated allowed tools."
    )
    run_p.add_argument(
        "--side-effect",
        choices=[s.value for s in SideEffectClass],
        default=SideEffectClass.WRITE.value,
    )
    run_p.add_argument(
        "--no-kill-on-secret", action="store_true", help="Don't kill on secret exposure."
    )
    run_p.add_argument("--timeout", type=int, default=3600, help="Max session duration (seconds).")
    run_p.add_argument("command", help="The command to run.")

    # `config` was removed. Read `_removed_config` before adding anything of the same shape back.
    cfg_p = sub.add_parser(
        "config",
        help="REMOVED. Use `warrantor agents wire <harness> <warrant-id>` instead.",
    )
    cfg_p.add_argument("--agent", default=None)
    cfg_p.add_argument("--dir", default=".")

    args = p.parse_args(argv)

    if args.cmd == "config":
        return _removed_config()

    if args.cmd == "run":
        config = HarnessConfig(
            agent_type=AgentType(args.agent),
            working_dir=args.dir,
            allowed_tools=args.tools.split(","),
            side_effect_class=SideEffectClass(args.side_effect),
            kill_on_secret_exposure=not args.no_kill_on_secret,
            max_duration_seconds=args.timeout,
        )
        with secure_session(config) as session:
            result = session.run_agent(args.command)
        summary = session.result.to_dict()
        summary["last_command_result"] = {
            "exit_code": result.get("exit_code", -1),
            "secrets_found": result.get("secrets_found", []),
        }
        json.dump(summary, sys.stdout, indent=2)
        sys.stdout.write("\n")
        return 0 if summary["status"] == "completed" else 1

    return 2


_REMOVED_MESSAGE = """warrantor-harness config has been REMOVED.

It wrote CLAUDE.md / AGENTS.md / .cursorrules files asserting that every action was
recorded, that secret exposure triggered a kill-switch, and that file access was
tracked. Nothing made those true. They were instructions to a model, and a security
boundary that lives in the prompt is the exact failure this project exists to refuse.

Use instead:
  warrantor agents list                          what can be wired, and what each
                                                 harness does NOT route through the
                                                 warrant
  warrantor agents wire <harness> <warrant-id>   the MCP configuration that actually
                                                 routes tool calls through it
"""


def _removed_config() -> int:
    """Refuse, and say what this used to do and why that was wrong.

    It wrote ``CLAUDE.md``, ``AGENTS.md`` or ``.cursorrules`` containing sentences like *"Every
    action is recorded as an Agent Action Receipt"*, *"Secret exposure triggers kill-switch
    (invariant I-09)"* and *"File access is tracked and logged"*.

    **Nothing in the system made any of those true.** They were instructions to a model -- a
    security boundary written into the context window while the substrate permitted whatever it
    permitted. That is the failure mode of all five frontier-lab intrusions this project's README
    is built on, and the reason the project exists. A false security claim, generated by us, into
    the file the agent reads first, is a worse defect than a missing feature.

    Replaced by ``warrantor agents wire``, which writes **MCP client configuration** routing the
    harness's tool calls through ``warrantor mcp --agent <id>`` -- a real boundary, because the
    calls traverse a process that can refuse them -- and which states, per harness, what does
    *not* go through it.

    Kept as an explicit refusal rather than deleted outright, so anyone who finds the old command
    in a script or a blog post reads this instead of a bare "invalid choice".
    """
    sys.stderr.write(
        _REMOVED_MESSAGE
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
