#!/usr/bin/env python3
"""Generate P1-P12 schemas, CDDL, and four-language type bindings.

`specs/protocols/registry.json` is the only editable shape registry. Generated
artifacts are deterministic and CI uses ``--check`` to reject drift.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import TypeAlias, cast

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = REPOSITORY_ROOT / "specs" / "protocols" / "registry.json"
PROTOCOLS_DIRECTORY = REGISTRY_PATH.parent
GENERATED_HEADER = "Generated by tools/protocols/generate.py; do not edit."

JsonScalar: TypeAlias = str | int | bool | None
JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]
JsonObject: TypeAlias = dict[str, JsonValue]


@dataclass(frozen=True)
class GeneratedArtifact:
    """One deterministic generated file."""

    path: Path
    content: str


def parse_arguments() -> argparse.Namespace:
    """Parse generator arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Write generated files")
    mode.add_argument("--check", action="store_true", help="Reject generated drift")
    return parser.parse_args()


def require_object(value: JsonValue, context: str) -> JsonObject:
    """Return a JSON object with string keys or fail with context."""

    if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
        raise ValueError(f"{context} must be an object")
    return cast(JsonObject, value)


def require_array(value: JsonValue, context: str) -> list[JsonValue]:
    """Return a JSON array or fail with context."""

    if not isinstance(value, list):
        raise ValueError(f"{context} must be an array")
    return value


def require_string(value: JsonValue, context: str) -> str:
    """Return a non-empty string or fail with context."""

    if not isinstance(value, str) or not value:
        raise ValueError(f"{context} must be a non-empty string")
    return value


def string_array(value: JsonValue, context: str) -> list[str]:
    """Return an array containing only non-empty strings."""

    items = require_array(value, context)
    return [require_string(item, f"{context}[]") for item in items]


def load_registry() -> JsonObject:
    """Load and validate registry-level uniqueness and references."""

    parsed = cast(JsonValue, json.loads(REGISTRY_PATH.read_text(encoding="utf-8")))
    registry = require_object(parsed, "registry")
    protocols = require_array(registry.get("protocols"), "registry.protocols")
    types = require_object(registry.get("types"), "registry.types")
    identifiers: set[str] = set()
    slugs: set[str] = set()
    type_names: set[str] = set()
    for index, raw_protocol in enumerate(protocols):
        protocol = require_object(raw_protocol, f"protocols[{index}]")
        identifier = require_string(protocol.get("id"), f"protocols[{index}].id")
        slug = require_string(protocol.get("slug"), f"protocols[{index}].slug")
        type_name = require_string(
            protocol.get("type_name"), f"protocols[{index}].type_name"
        )
        if identifier in identifiers or slug in slugs or type_name in type_names:
            raise ValueError(f"duplicate protocol identity at {identifier}")
        identifiers.add(identifier)
        slugs.add(slug)
        type_names.add(type_name)
        validate_shape(
            require_object(protocol.get("payload"), f"{identifier}.payload"),
            types,
            f"{identifier}.payload",
        )
    validate_shape(
        require_object(registry.get("common"), "registry.common"),
        types,
        "registry.common",
    )
    for type_name, raw_shape in types.items():
        validate_shape(require_object(raw_shape, f"types.{type_name}"), types, type_name)
    if identifiers != {f"P{number}" for number in range(1, 13)}:
        raise ValueError("registry must contain exactly P1 through P12")
    return registry


def validate_shape(shape: JsonObject, types: JsonObject, context: str) -> None:
    """Validate one object shape and every recursive field descriptor."""

    required = set(string_array(shape.get("required"), f"{context}.required"))
    properties = require_object(shape.get("properties"), f"{context}.properties")
    if not required <= properties.keys():
        missing = sorted(required - properties.keys())
        raise ValueError(f"{context} required fields lack descriptors: {missing}")
    for field_name, raw_descriptor in properties.items():
        validate_descriptor(
            require_object(raw_descriptor, f"{context}.{field_name}"),
            types,
            f"{context}.{field_name}",
        )


def validate_descriptor(
    descriptor: JsonObject, types: JsonObject, context: str
) -> None:
    """Validate a recursive field descriptor used by generators and runtimes."""

    reference = descriptor.get("$ref")
    if reference is not None:
        reference_name = require_string(reference, f"{context}.$ref")
        if reference_name not in types:
            raise ValueError(f"{context} references unknown type {reference_name}")
        if set(descriptor) != {"$ref"}:
            raise ValueError(f"{context} reference cannot contain sibling constraints")
        return
    field_type = require_string(descriptor.get("type"), f"{context}.type")
    if field_type not in {"string", "integer", "boolean", "array", "object"}:
        raise ValueError(f"{context} has unsupported type {field_type}")
    if field_type == "array":
        validate_descriptor(
            require_object(descriptor.get("items"), f"{context}.items"),
            types,
            f"{context}.items",
        )
    if field_type == "object" and descriptor.get("additionalProperties") is not True:
        validate_shape(descriptor, types, context)


def json_schema_descriptor(descriptor: JsonObject) -> JsonObject:
    """Convert a registry descriptor into JSON Schema 2020-12."""

    reference = descriptor.get("$ref")
    if isinstance(reference, str):
        return {"$ref": f"#/$defs/{reference}"}
    converted: JsonObject = {}
    for key, value in descriptor.items():
        if key == "items":
            converted[key] = json_schema_descriptor(
                require_object(value, "array item descriptor")
            )
        elif key in {"required", "properties"} and descriptor.get("type") == "object":
            continue
        else:
            converted[key] = value
    if descriptor.get("type") == "object" and descriptor.get("additionalProperties") is not True:
        nested = object_schema(descriptor)
        converted.update(nested)
    return converted


def object_schema(shape: JsonObject) -> JsonObject:
    """Convert a named registry object shape into JSON Schema."""

    required = string_array(shape.get("required"), "shape.required")
    properties = require_object(shape.get("properties"), "shape.properties")
    return {
        "type": "object",
        "additionalProperties": False,
        "required": required,
        "properties": {
            name: json_schema_descriptor(require_object(value, name))
            for name, value in properties.items()
        },
    }


def protocol_schema(registry: JsonObject, protocol: JsonObject) -> JsonObject:
    """Build the standalone JSON Schema for one signed protocol envelope."""

    identifier = require_string(protocol.get("id"), "protocol.id")
    slug = require_string(protocol.get("slug"), "protocol.slug")
    title = require_string(protocol.get("title"), "protocol.title")
    common = require_object(registry.get("common"), "registry.common")
    common_schema = object_schema(common)
    properties = require_object(common_schema["properties"], "common properties")
    properties["protocol"] = {"const": identifier}
    properties["payload"] = object_schema(
        require_object(protocol.get("payload"), f"{identifier}.payload")
    )
    definitions = require_object(registry.get("types"), "registry.types")
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"https://muveraai.com/schemas/protocols/v1/{slug}.schema.json",
        "title": f"AumOS P{identifier[1:]} {title} v1 envelope",
        **common_schema,
        "$defs": {
            name: object_schema(require_object(shape, f"types.{name}"))
            for name, shape in definitions.items()
        },
    }


def pascal_case(value: str) -> str:
    """Convert snake/kebab identifiers to deterministic PascalCase."""

    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[_-]", value))


def camel_case(value: str) -> str:
    """Convert snake/kebab identifiers to deterministic lowerCamelCase."""

    converted = pascal_case(value)
    return converted[:1].lower() + converted[1:]


def enum_values(descriptor: JsonObject) -> list[str]:
    """Return string enum or const values for binding generation."""

    constant = descriptor.get("const")
    if isinstance(constant, str):
        return [constant]
    raw_values = descriptor.get("enum")
    if isinstance(raw_values, list) and all(isinstance(item, str) for item in raw_values):
        return cast(list[str], raw_values)
    return []


def typescript_type(descriptor: JsonObject) -> str:
    """Map one descriptor to strict TypeScript."""

    reference = descriptor.get("$ref")
    if isinstance(reference, str):
        return reference
    values = enum_values(descriptor)
    if values:
        return " | ".join(json.dumps(value) for value in values)
    field_type = descriptor.get("type")
    if field_type == "string":
        return "string"
    if field_type == "integer":
        return "number"
    if field_type == "boolean":
        return "boolean"
    if field_type == "array":
        item = require_object(descriptor.get("items"), "array items")
        item_type = typescript_type(item)
        if " | " in item_type:
            item_type = f"({item_type})"
        return f"readonly {item_type}[]"
    if field_type == "object":
        return "Readonly<Record<string, JsonValue>>"
    raise ValueError(f"unsupported TypeScript descriptor: {descriptor}")


def python_type(descriptor: JsonObject) -> str:
    """Map one descriptor to a Python typing expression."""

    reference = descriptor.get("$ref")
    if isinstance(reference, str):
        return reference
    values = enum_values(descriptor)
    if values:
        return "Literal[" + ", ".join(json.dumps(value) for value in values) + "]"
    field_type = descriptor.get("type")
    if field_type == "string":
        return "str"
    if field_type == "integer":
        return "int"
    if field_type == "boolean":
        return "bool"
    if field_type == "array":
        item = require_object(descriptor.get("items"), "array items")
        return f"list[{python_type(item)}]"
    if field_type == "object":
        return "dict[str, JsonValue]"
    raise ValueError(f"unsupported Python descriptor: {descriptor}")


def go_type(descriptor: JsonObject) -> str:
    """Map one descriptor to Go."""

    reference = descriptor.get("$ref")
    if isinstance(reference, str):
        return reference
    field_type = descriptor.get("type")
    if field_type == "string":
        return "string"
    if field_type == "integer":
        return "uint64"
    if field_type == "boolean":
        return "bool"
    if field_type == "array":
        item = require_object(descriptor.get("items"), "array items")
        return f"[]{go_type(item)}"
    if field_type == "object":
        return "map[string]JSONValue"
    raise ValueError(f"unsupported Go descriptor: {descriptor}")


def rust_type(descriptor: JsonObject) -> str:
    """Map one descriptor to Rust."""

    reference = descriptor.get("$ref")
    if isinstance(reference, str):
        return reference
    field_type = descriptor.get("type")
    if field_type == "string":
        return "String"
    if field_type == "integer":
        return "u64"
    if field_type == "boolean":
        return "bool"
    if field_type == "array":
        item = require_object(descriptor.get("items"), "array items")
        return f"Vec<{rust_type(item)}>"
    if field_type == "object":
        return "BTreeMap<String, serde_json::Value>"
    raise ValueError(f"unsupported Rust descriptor: {descriptor}")


def binding_shapes(registry: JsonObject) -> list[tuple[str, JsonObject]]:
    """Return named common and protocol payload shapes in stable order."""

    types = require_object(registry.get("types"), "registry.types")
    shapes = [(name, require_object(shape, f"types.{name}")) for name, shape in types.items()]
    for raw_protocol in require_array(registry.get("protocols"), "protocols"):
        protocol = require_object(raw_protocol, "protocol")
        shapes.append(
            (
                require_string(protocol.get("type_name"), "protocol.type_name"),
                require_object(protocol.get("payload"), "protocol.payload"),
            )
        )
    return shapes


def generate_typescript(registry: JsonObject) -> str:
    """Generate strict, named TypeScript bindings."""

    lines = [
        f"/** {GENERATED_HEADER} */",
        "",
        "export type JsonScalar = string | number | boolean | null;",
        # `JsonObject` must be an interface: a mapped type such as
        # `Readonly<Record<string, JsonValue>>` resolves eagerly and makes this
        # self-referential alias circular (TS2456).
        "export interface JsonObject { readonly [key: string]: JsonValue }",
        "export type JsonValue = JsonScalar | readonly JsonValue[] | JsonObject;",
        "export type ProtocolId = 'P1' | 'P2' | 'P3' | 'P4' | 'P5' | 'P6' | 'P7' | 'P8' | 'P9' | 'P10' | 'P11' | 'P12';",
        "",
        "export interface ProtocolEnvelope<TPayload> {",
        "  readonly protocol: ProtocolId;",
        "  readonly version: '1.0.0';",
        "  readonly message_id: string;",
        "  readonly issuer: string;",
        "  readonly issued_at: number;",
        "  readonly expires_at: number;",
        "  readonly nonce: string;",
        "  readonly payload: TPayload;",
        "  readonly critical_extensions: readonly string[];",
        "  readonly extensions: Readonly<Record<string, JsonValue>>;",
        "  readonly signature: Signature;",
        "}",
        "",
    ]
    for name, shape in binding_shapes(registry):
        lines.append(f"export interface {name} {{")
        properties = require_object(shape.get("properties"), f"{name}.properties")
        for field_name, raw_descriptor in properties.items():
            descriptor = require_object(raw_descriptor, field_name)
            lines.append(
                f"  readonly {field_name}: {typescript_type(descriptor)};"
            )
        lines.extend(["}", ""])
    for raw_protocol in require_array(registry.get("protocols"), "protocols"):
        protocol = require_object(raw_protocol, "protocol")
        lines.append(
            "export type "
            + require_string(protocol.get("type_name"), "type_name").removesuffix("Payload")
            + " = ProtocolEnvelope<"
            + require_string(protocol.get("type_name"), "type_name")
            + ">;"
        )
    return "\n".join(lines) + "\n"


def generate_python(registry: JsonObject) -> str:
    """Generate Python TypedDict bindings with complete annotations."""

    lines = [
        f'"""{GENERATED_HEADER}"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Generic, Literal, TypeAlias, TypeVar, TypedDict",
        "",
        "JsonScalar: TypeAlias = str | int | bool | None",
        'JsonValue: TypeAlias = JsonScalar | list["JsonValue"] | dict[str, "JsonValue"]',
        "ProtocolId: TypeAlias = Literal[\"P1\", \"P2\", \"P3\", \"P4\", \"P5\", \"P6\", \"P7\", \"P8\", \"P9\", \"P10\", \"P11\", \"P12\"]",
        "PayloadT = TypeVar(\"PayloadT\")",
        "",
    ]
    for name, shape in binding_shapes(registry):
        lines.append(f"class {name}(TypedDict):")
        properties = require_object(shape.get("properties"), f"{name}.properties")
        for field_name, raw_descriptor in properties.items():
            descriptor = require_object(raw_descriptor, field_name)
            lines.append(f"    {field_name}: {python_type(descriptor)}")
        lines.append("")
    lines.extend(
        [
            "class ProtocolEnvelope(TypedDict, Generic[PayloadT]):",
            "    protocol: ProtocolId",
            '    version: Literal["1.0.0"]',
            "    message_id: str",
            "    issuer: str",
            "    issued_at: int",
            "    expires_at: int",
            "    nonce: str",
            "    payload: PayloadT",
            "    critical_extensions: list[str]",
            "    extensions: dict[str, JsonValue]",
            "    signature: Signature",
            "",
        ]
    )
    for raw_protocol in require_array(registry.get("protocols"), "protocols"):
        protocol = require_object(raw_protocol, "protocol")
        type_name = require_string(protocol.get("type_name"), "type_name")
        alias = type_name.removesuffix("Payload")
        lines.append(f"{alias}: TypeAlias = ProtocolEnvelope[{type_name}]")
    return "\n".join(lines) + "\n"


def generate_go(registry: JsonObject) -> str:
    """Generate Go generic envelope and named payload structs."""

    lines = [
        f"// {GENERATED_HEADER}",
        "package protocolcontracts",
        "",
        "type JSONValue interface{}",
        "",
        "type ProtocolEnvelope[Payload any] struct {",
        '\tProtocol\tstring\t`json:"protocol"`',
        '\tVersion\tstring\t`json:"version"`',
        '\tMessageID\tstring\t`json:"message_id"`',
        '\tIssuer\tstring\t`json:"issuer"`',
        '\tIssuedAt\tuint64\t`json:"issued_at"`',
        '\tExpiresAt\tuint64\t`json:"expires_at"`',
        '\tNonce\tstring\t`json:"nonce"`',
        '\tPayload\tPayload\t`json:"payload"`',
        '\tCriticalExtensions\t[]string\t`json:"critical_extensions"`',
        '\tExtensions\tmap[string]JSONValue\t`json:"extensions"`',
        '\tSignature\tSignature\t`json:"signature"`',
        "}",
        "",
    ]
    for name, shape in binding_shapes(registry):
        lines.append(f"type {name} struct {{")
        properties = require_object(shape.get("properties"), f"{name}.properties")
        for field_name, raw_descriptor in properties.items():
            descriptor = require_object(raw_descriptor, field_name)
            lines.append(
                f'\t{pascal_case(field_name)}\t{go_type(descriptor)}\t`json:"{field_name}"`'
            )
        lines.extend(["}", ""])
    for raw_protocol in require_array(registry.get("protocols"), "protocols"):
        protocol = require_object(raw_protocol, "protocol")
        type_name = require_string(protocol.get("type_name"), "type_name")
        alias = type_name.removesuffix("Payload")
        lines.append(f"type {alias} ProtocolEnvelope[{type_name}]")
    source = "\n".join(lines) + "\n"
    gofmt = shutil.which("gofmt")
    if gofmt is None:
        raise ValueError("gofmt is required to generate deterministic Go bindings")
    completed = subprocess.run(
        [gofmt],
        input=source,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise ValueError(f"gofmt rejected generated bindings: {completed.stderr.strip()}")
    return completed.stdout


def generate_rust(registry: JsonObject) -> str:
    """Generate Rust serde bindings with unknown-field rejection."""

    lines = [
        f"//! {GENERATED_HEADER}",
        "",
        "use serde::{Deserialize, Serialize};",
        "use std::collections::BTreeMap;",
        "",
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
        "#[serde(deny_unknown_fields)]",
        "pub struct ProtocolEnvelope<Payload> {",
        "    pub protocol: String,",
        "    pub version: String,",
        "    pub message_id: String,",
        "    pub issuer: String,",
        "    pub issued_at: u64,",
        "    pub expires_at: u64,",
        "    pub nonce: String,",
        "    pub payload: Payload,",
        "    pub critical_extensions: Vec<String>,",
        "    pub extensions: BTreeMap<String, serde_json::Value>,",
        "    pub signature: Signature,",
        "}",
        "",
    ]
    for name, shape in binding_shapes(registry):
        lines.extend(
            [
                "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
                "#[serde(deny_unknown_fields)]",
                f"pub struct {name} {{",
            ]
        )
        properties = require_object(shape.get("properties"), f"{name}.properties")
        for field_name, raw_descriptor in properties.items():
            descriptor = require_object(raw_descriptor, field_name)
            lines.append(f"    pub {field_name}: {rust_type(descriptor)},")
        lines.extend(["}", ""])
    for raw_protocol in require_array(registry.get("protocols"), "protocols"):
        protocol = require_object(raw_protocol, "protocol")
        type_name = require_string(protocol.get("type_name"), "type_name")
        alias = type_name.removesuffix("Payload")
        lines.append(f"pub type {alias} = ProtocolEnvelope<{type_name}>;")
    return "\n".join(lines) + "\n"


def cddl_type(descriptor: JsonObject) -> str:
    """Map a descriptor to RFC 8610 CDDL syntax."""

    reference = descriptor.get("$ref")
    if isinstance(reference, str):
        return reference
    values = enum_values(descriptor)
    if values:
        return " / ".join(json.dumps(value) for value in values)
    field_type = descriptor.get("type")
    if field_type == "string":
        pattern = descriptor.get("pattern")
        return f"tstr .regexp {json.dumps(pattern)}" if isinstance(pattern, str) else "tstr"
    if field_type == "integer":
        minimum = descriptor.get("minimum")
        maximum = descriptor.get("maximum")
        if isinstance(minimum, int) and isinstance(maximum, int):
            return f"{minimum}..{maximum}"
        if isinstance(minimum, int) and minimum >= 0:
            return "uint"
        return "int"
    if field_type == "boolean":
        return "bool"
    if field_type == "array":
        item = require_object(descriptor.get("items"), "array items")
        minimum = descriptor.get("minItems")
        prefix = "+" if isinstance(minimum, int) and minimum > 0 else "*"
        return f"[{prefix} {cddl_type(item)}]"
    if field_type == "object":
        return "{ * tstr => any }"
    raise ValueError(f"unsupported CDDL descriptor: {descriptor}")


def cddl_shape(name: str, shape: JsonObject) -> list[str]:
    """Render a named CDDL map."""

    properties = require_object(shape.get("properties"), f"{name}.properties")
    required = set(string_array(shape.get("required"), f"{name}.required"))
    lines = [f"{name} = {{"]
    for field_name, raw_descriptor in properties.items():
        marker = "" if field_name in required else "? "
        lines.append(
            f"  {marker}{field_name}: {cddl_type(require_object(raw_descriptor, field_name))},"
        )
    lines.append("}")
    return lines


def generate_cddl(registry: JsonObject, protocol: JsonObject) -> str:
    """Generate a standalone CDDL contract for one protocol envelope."""

    identifier = require_string(protocol.get("id"), "protocol.id")
    slug = require_string(protocol.get("slug"), "protocol.slug")
    title = require_string(protocol.get("title"), "protocol.title")
    lines = [
        f"; {GENERATED_HEADER}",
        f"; {identifier} - {title}; JSON profile has equivalent shape.",
        f"{slug}_envelope = {{",
        f'  protocol: "{identifier}",',
        '  version: "1.0.0",',
        "  message_id: tstr,",
        "  issuer: tstr,",
        "  issued_at: uint,",
        "  expires_at: uint,",
        "  nonce: tstr .regexp \"^[0-9a-f]{64}$\",",
        f"  payload: {slug}_payload,",
        "  critical_extensions: [* tstr],",
        "  extensions: { * tstr => any },",
        "  signature: Signature,",
        "}",
        "",
    ]
    lines.extend(
        cddl_shape(
            f"{slug}_payload",
            require_object(protocol.get("payload"), f"{identifier}.payload"),
        )
    )
    for name, shape in binding_shapes(registry)[: len(require_object(registry.get("types"), "types"))]:
        lines.append("")
        lines.extend(cddl_shape(name, shape))
    return "\n".join(lines) + "\n"


def markdown_normative_block(registry: JsonObject, protocol: JsonObject) -> str:
    """Return the registry-derived mandatory-field list for a protocol spec.

    The envelope fields are common to every protocol; the payload fields come from
    the protocol's own ``payload.required``. Both are read from ``registry.json``,
    which is the single normative source.
    """

    common = require_object(registry.get("common"), "common")
    envelope = [f for f in require_array(common.get("required"), "common.required")
                if f not in ("payload", "signature")]
    payload = require_array(
        require_object(protocol.get("payload"), "protocol.payload").get("required"),
        "protocol.payload.required",
    )
    return (
        "envelope: " + ", ".join(str(f) for f in envelope) + "\n"
        "payload:  " + ", ".join(str(f) for f in payload) + "\n"
        "signature: algorithm, key_id, value"
    )


def patch_protocol_markdown(registry: JsonObject, protocol: JsonObject, existing: str) -> str:
    """Rewrite the registry-derived parts of a protocol's Markdown spec.

    Authored prose is preserved. Four things are corrected, because each was a
    live source of implementation divergence:

    1. ``Mandatory fields`` -- was hand-written and disagreed with ``registry.json``
       for all twelve protocols. Two implementations (``typescript/mcp-gateway`` and
       ``rust/authority-spec``) were built to the prose names and are wire-
       incompatible with the schema the validator enforces.
    2. ``Schema location`` -- pointed at ``proto/warrantor/protocols/v1/*.proto`` files
       that do not exist for ten of twelve protocols.
    3. The adversarial-vector path -- pointed at ``testvectors/{ID}/``; the vectors
       actually live in ``testvectors/protocols/{ID}/``.
    4. The conformance sentence -- claimed enforcement "against every language
       implementation"; the vectors run in Rust and Python only.
    """

    identifier = require_string(protocol.get("id"), "protocol.id")
    slug = require_string(protocol.get("slug"), "protocol.slug")
    schema_ref = f"specs/protocols/{identifier}-{slug}.schema.json + .cddl"
    text = existing

    # 1. Mandatory-field block, regenerated from the registry.
    block = markdown_normative_block(registry, protocol)
    text = re.sub(
        r"(The normative schema lives at `[^`]*`\. Mandatory fields:\n\n```\n)"
        r".*?(\n```)",
        lambda m: m.group(1) + block + m.group(2),
        text,
        count=1,
        flags=re.S,
    )

    # 2. Schema location -- both the table row and the prose sentence.
    text = re.sub(
        r"(\| \*\*Schema location\*\* \| `)[^`]*(` \|)",
        lambda m: m.group(1) + schema_ref + m.group(2),
        text,
        count=1,
    )
    text = re.sub(
        r"(The normative schema lives at `)[^`]*(`\. Mandatory fields:)",
        lambda m: m.group(1) + schema_ref + m.group(2),
        text,
        count=1,
    )

    # 3. Adversarial vector path.
    text = text.replace(
        f"testvectors/{identifier}/", f"testvectors/protocols/{identifier}/"
    )
    text = text.replace(
        "testvectors/protocols/protocols/", "testvectors/protocols/"
    )

    # 4. The conformance claim, stated accurately.
    text = text.replace(
        "Conformance is enforced by A6 (the cross-language conformance suite) against every language\n"
        "implementation that consumes the protocol.",
        "Conformance is enforced by the protocol vector suite in\n"
        "[`testvectors/protocols/`](../../testvectors/protocols/). Coverage by language is reported by\n"
        "`tools/conformance/run.py`; a language absent from that report has not been verified against\n"
        "these vectors.",
    )
    return text


def generated_artifacts(registry: JsonObject) -> list[GeneratedArtifact]:
    """Construct every generated output in stable order."""

    artifacts: list[GeneratedArtifact] = []
    for raw_protocol in require_array(registry.get("protocols"), "protocols"):
        protocol = require_object(raw_protocol, "protocol")
        identifier = require_string(protocol.get("id"), "protocol.id")
        slug = require_string(protocol.get("slug"), "protocol.slug")
        schema = protocol_schema(registry, protocol)
        artifacts.append(
            GeneratedArtifact(
                PROTOCOLS_DIRECTORY / f"{identifier}-{slug}.schema.json",
                json.dumps(schema, indent=2, ensure_ascii=False) + "\n",
            )
        )
        artifacts.append(
            GeneratedArtifact(
                PROTOCOLS_DIRECTORY / f"{identifier}-{slug}.cddl",
                generate_cddl(registry, protocol),
            )
        )
        markdown_path = PROTOCOLS_DIRECTORY / f"{identifier}-{slug}.md"
        if markdown_path.is_file():
            artifacts.append(
                GeneratedArtifact(
                    markdown_path,
                    patch_protocol_markdown(
                        registry,
                        protocol,
                        markdown_path.read_text(encoding="utf-8"),
                    ),
                )
            )
    artifacts.extend(
        [
            GeneratedArtifact(
                REPOSITORY_ROOT
                / "typescript"
                / "protocol-contracts"
                / "src"
                / "generated.ts",
                generate_typescript(registry),
            ),
            GeneratedArtifact(
                REPOSITORY_ROOT
                / "python"
                / "protocol_contracts"
                / "src"
                / "protocol_contracts"
                / "generated.py",
                generate_python(registry),
            ),
            GeneratedArtifact(
                REPOSITORY_ROOT / "go" / "protocol-contracts" / "generated.go",
                generate_go(registry),
            ),
            GeneratedArtifact(
                REPOSITORY_ROOT
                / "rust"
                / "protocol-contracts"
                / "src"
                / "generated.rs",
                generate_rust(registry),
            ),
        ]
    )
    return artifacts


def write_artifacts(artifacts: list[GeneratedArtifact]) -> None:
    """Write all generated outputs."""

    for artifact in artifacts:
        artifact.path.parent.mkdir(parents=True, exist_ok=True)
        artifact.path.write_text(artifact.content, encoding="utf-8", newline="\n")
        print(f"generated {artifact.path.relative_to(REPOSITORY_ROOT)}")


def check_artifacts(artifacts: list[GeneratedArtifact]) -> int:
    """Return non-zero if any generated output is missing or stale."""

    stale: list[Path] = []
    for artifact in artifacts:
        if not artifact.path.is_file() or artifact.path.read_text(
            encoding="utf-8"
        ) != artifact.content:
            stale.append(artifact.path)
    if stale:
        for path in stale:
            print(f"stale generated protocol artifact: {path.relative_to(REPOSITORY_ROOT)}")
        return 1
    print(f"protocol generation: PASS - {len(artifacts)} artifacts are current")
    return 0


def main() -> int:
    """Generate or verify all protocol contract artifacts."""

    arguments = parse_arguments()
    try:
        registry = load_registry()
        artifacts = generated_artifacts(registry)
        if arguments.write:
            write_artifacts(artifacts)
            return 0
        return check_artifacts(artifacts)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"protocol generation failed: {error}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
