/** Generated by tools/protocols/generate.py; do not edit. */

export type JsonScalar = string | number | boolean | null;
export interface JsonObject { readonly [key: string]: JsonValue }
export type JsonValue = JsonScalar | readonly JsonValue[] | JsonObject;
export type ProtocolId = 'P1' | 'P2' | 'P3' | 'P4' | 'P5' | 'P6' | 'P7' | 'P8' | 'P9' | 'P10' | 'P11' | 'P12';

export interface ProtocolEnvelope<TPayload> {
  readonly protocol: ProtocolId;
  readonly version: '1.0.0';
  readonly message_id: string;
  readonly issuer: string;
  readonly issued_at: number;
  readonly expires_at: number;
  readonly nonce: string;
  readonly payload: TPayload;
  readonly critical_extensions: readonly string[];
  readonly extensions: Readonly<Record<string, JsonValue>>;
  readonly signature: Signature;
}

export interface Signature {
  readonly algorithm: "Ed25519";
  readonly key_id: string;
  readonly value: string;
}

export interface ArtifactReference {
  readonly uri: string;
  readonly digest: string;
  readonly media_type: string;
  readonly version: string;
  readonly license: string;
}

export interface Budget {
  readonly steps: number;
  readonly wall_clock_seconds: number;
  readonly tokens: number;
  readonly money_minor: number;
  readonly external_calls: number;
  readonly data_bytes: number;
  readonly irreversible_actions: number;
}

export interface PolicyDecision {
  readonly engine: "opa" | "cedar" | "openshell";
  readonly decision: "allow" | "deny";
  readonly policy_digest: string;
  readonly matched_rules: readonly string[];
}

export interface DeterministicCheck {
  readonly name: string;
  readonly passed: boolean;
  readonly detail_digest: string;
}

export interface Transformation {
  readonly operation: string;
  readonly implementation: string;
  readonly input_digest: string;
  readonly output_digest: string;
  readonly applied_at: number;
}

export interface EvaluationAssertion {
  readonly name: string;
  readonly expected_digest: string;
  readonly actual_digest: string;
  readonly passed: boolean;
}

export interface NetworkPolicy {
  readonly egress_default: "deny" | "allow";
  readonly allowlist: readonly string[];
  readonly blocklist: readonly string[];
  readonly dns_policy: "deny" | "allowlisted";
}

export interface AgentAuthorityEnvelopePayload {
  readonly subject: string;
  readonly purpose: string;
  readonly resources: readonly string[];
  readonly tools: readonly string[];
  readonly data_classes: readonly ("L0" | "L1" | "L2" | "L3" | "L4")[];
  readonly side_effect_class: "read" | "write" | "financial" | "destructive" | "physical";
  readonly budget: Budget;
  readonly geographies: readonly string[];
  readonly delegation_depth: number;
  readonly approvals: readonly string[];
  readonly revocation_handle: string;
}

export interface AgentActionReceiptPayload {
  readonly phase: "precommit" | "final";
  readonly actor: string;
  readonly authority_digest: string;
  readonly artifact_digests: readonly string[];
  readonly context_digest: string;
  readonly policy_decision: PolicyDecision;
  readonly operation: string;
  readonly checks: readonly DeterministicCheck[];
  readonly approvers: readonly string[];
  readonly outcome: "pending" | "committed" | "rolled_back" | "failed";
  readonly rollback_pointer: string;
  readonly parent_receipt: string;
}

export interface ContextProvenanceEnvelopePayload {
  readonly source_identity: string;
  readonly acquired_at: number;
  readonly consent: boolean;
  readonly sensitivity: "L0" | "L1" | "L2" | "L3" | "L4";
  readonly content_digest: string;
  readonly confidence_micros: number;
  readonly transformations: readonly Transformation[];
  readonly derived_from: readonly string[];
  readonly taints: readonly ("untrusted" | "pii" | "sensitive" | "malware")[];
  readonly allowed_uses: readonly string[];
}

export interface AgentMemoryIntegrityRecordPayload {
  readonly sequence: number;
  readonly previous_digest: string;
  readonly owner: string;
  readonly content_digest: string;
  readonly confidence_micros: number;
  readonly contradiction_links: readonly string[];
  readonly provenance_digest: string;
  readonly quarantine_state: "clean" | "quarantined" | "resolved";
  readonly supersedes: string;
  readonly retention_until: number;
  readonly consent_revoked: boolean;
}

export interface SecureSkillPackagePayload {
  readonly name: string;
  readonly package: ArtifactReference;
  readonly instructions_digest: string;
  readonly code: ArtifactReference;
  readonly runtime: "wasm" | "python" | "node" | "container";
  readonly tools: readonly string[];
  readonly permissions: readonly string[];
  readonly publisher_identity: string;
  readonly ai_sbom: ArtifactReference;
  readonly evaluation_bundle: ArtifactReference;
  readonly limitations: readonly string[];
  readonly revocation_handle: string;
}

export interface AiArtifactTrustManifestPayload {
  readonly artifacts: readonly ArtifactReference[];
  readonly roles: readonly ("model" | "dataset" | "tokenizer" | "prompt" | "adapter" | "container" | "policy" | "skill" | "evaluation")[];
  readonly root_digest: string;
  readonly build_provenance: ArtifactReference;
  readonly deployment_attestations: readonly ArtifactReference[];
}

export interface AutonomyBudgetSpecificationPayload {
  readonly budget: Budget;
  readonly currency: string;
  readonly privilege: "none" | "read" | "write" | "admin";
  readonly expected_risk_micros: number;
  readonly approval_required: boolean;
  readonly replenishment: "none" | "manual" | "scheduled";
}

export interface VerifiableEvaluationBundlePayload {
  readonly corpus: ArtifactReference;
  readonly environment: ArtifactReference;
  readonly model: ArtifactReference;
  readonly harness: ArtifactReference;
  readonly policy: ArtifactReference;
  readonly seeds: readonly number[];
  readonly trace_digests: readonly string[];
  readonly judge: ArtifactReference;
  readonly assertions: readonly EvaluationAssertion[];
  readonly passed_count: number;
  readonly failed_count: number;
}

export interface AgentIncidentExchangePayload {
  readonly incident_type: "goal_hijack" | "memory_poisoning" | "tool_abuse" | "identity_compromise" | "exfiltration" | "rogue_delegation";
  readonly severity: "info" | "low" | "medium" | "high" | "critical";
  readonly agent: string;
  readonly authority_digest: string;
  readonly evidence_refs: readonly string[];
  readonly mitre_atlas_ids: readonly string[];
  readonly ocsf_class_uid: number;
  readonly detected_at: number;
  readonly contained_at: number;
  readonly containment_status: "open" | "contained" | "eradicated" | "recovered";
}

export interface MultiAgentDelegationExchangePayload {
  readonly delegator: string;
  readonly delegatee: string;
  readonly parent_authority_digest: string;
  readonly delegation_chain: readonly string[];
  readonly hop_count: number;
  readonly max_depth: number;
  readonly capabilities: readonly string[];
  readonly parent_budget: Budget;
  readonly delegated_budget: Budget;
  readonly quorum: number;
  readonly approvals: readonly string[];
  readonly evidence_requirements: readonly string[];
  readonly result_digest: string;
  readonly status: "offered" | "accepted" | "completed" | "rejected" | "revoked";
}

export interface ProofCarryingRemediationBundlePayload {
  readonly reproducer: ArtifactReference;
  readonly root_cause_digest: string;
  readonly affected_versions: readonly string[];
  readonly patch: ArtifactReference;
  readonly tests: readonly ArtifactReference[];
  readonly regression_evidence: ArtifactReference;
  readonly build_provenance: ArtifactReference;
  readonly embargo_until: number;
  readonly disclosure_status: "embargoed" | "coordinated" | "public";
}

export interface CapabilityAttestationProfilePayload {
  readonly subject: string;
  readonly runtime: string;
  readonly tools: readonly string[];
  readonly policy_digest: string;
  readonly credential_types: readonly string[];
  readonly network: NetworkPolicy;
  readonly memory_isolation: "process" | "container" | "wasm" | "tee";
  readonly model: ArtifactReference;
  readonly sandbox: "wasm" | "container" | "tee";
  readonly attestation_evidence: ArtifactReference;
  readonly valid_until: number;
}

export type AgentAuthorityEnvelope = ProtocolEnvelope<AgentAuthorityEnvelopePayload>;
export type AgentActionReceipt = ProtocolEnvelope<AgentActionReceiptPayload>;
export type ContextProvenanceEnvelope = ProtocolEnvelope<ContextProvenanceEnvelopePayload>;
export type AgentMemoryIntegrityRecord = ProtocolEnvelope<AgentMemoryIntegrityRecordPayload>;
export type SecureSkillPackage = ProtocolEnvelope<SecureSkillPackagePayload>;
export type AiArtifactTrustManifest = ProtocolEnvelope<AiArtifactTrustManifestPayload>;
export type AutonomyBudgetSpecification = ProtocolEnvelope<AutonomyBudgetSpecificationPayload>;
export type VerifiableEvaluationBundle = ProtocolEnvelope<VerifiableEvaluationBundlePayload>;
export type AgentIncidentExchange = ProtocolEnvelope<AgentIncidentExchangePayload>;
export type MultiAgentDelegationExchange = ProtocolEnvelope<MultiAgentDelegationExchangePayload>;
export type ProofCarryingRemediationBundle = ProtocolEnvelope<ProofCarryingRemediationBundlePayload>;
export type CapabilityAttestationProfile = ProtocolEnvelope<CapabilityAttestationProfilePayload>;
